// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               v7.35.0
// source: ai.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "AI_SERVICE";

export interface GetReviewSummaryRequest {
  processId?: string | undefined;
  productId: string;
}

export interface GenerateReviewSummaryRequest {
  processId?: string | undefined;
  productId: string;
}

export interface ReviewSummaryResponse {
  id: string;
  productId: string;
  pros: string[];
  cons: string[];
  summary: string;
  reviewCount: number;
  lastReviewAt: string;
  createdAt: string;
  updatedAt: string;
}

export const AI_SERVICE_PACKAGE_NAME = "AI_SERVICE";

export interface ReviewSummaryModuleClient {
  getReviewSummary(request: GetReviewSummaryRequest): Observable<ReviewSummaryResponse>;

  generateReviewSummary(request: GenerateReviewSummaryRequest): Observable<ReviewSummaryResponse>;
}

export interface ReviewSummaryModuleController {
  getReviewSummary(
    request: GetReviewSummaryRequest,
  ): Promise<ReviewSummaryResponse> | Observable<ReviewSummaryResponse> | ReviewSummaryResponse;

  generateReviewSummary(
    request: GenerateReviewSummaryRequest,
  ): Promise<ReviewSummaryResponse> | Observable<ReviewSummaryResponse> | ReviewSummaryResponse;
}

export function ReviewSummaryModuleControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["getReviewSummary", "generateReviewSummary"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("ReviewSummaryModule", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("ReviewSummaryModule", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const REVIEW_SUMMARY_MODULE_SERVICE_NAME = "ReviewSummaryModule";
