// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               v7.34.1
// source: cart.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "CART_SERVICE";

/** ==================== AddCartItem ====================// */
export interface AddCartItemRequest {
  processId?: string | undefined;
  userId: string;
  productId: string;
  skuId: string;
  shopId: string;
  quantity: number;
  skuValue: string;
  productName: string;
  productImage?: string | undefined;
}

export interface CartItemResponse {
  id: string;
  cartId: string;
  productId: string;
  skuId: string;
  shopId: string;
  quantity: number;
  productName: string;
  skuValue: string;
  productImage: string;
  createdAt: string;
  updatedAt: string;
}

export interface CartResponse {
  cartItem: CartItemResponse | undefined;
  cartCount: number;
}

/** ==================== UpdateCartItem ====================// */
export interface UpdateCartItemRequest {
  processId?: string | undefined;
  userId: string;
  productId: string;
  skuId: string;
  shopId: string;
  quantity: number;
  skuValue: string;
  productName: string;
  productImage?: string | undefined;
}

/** ==================== DeleteCartItem ====================// */
export interface DeleteCartItemRequest {
  processId?: string | undefined;
  userId: string;
  cartItemId: string;
}

/** ==================== ValidateCartItems ====================// */
export interface ValidateCartItemsRequest {
  processId?: string | undefined;
  cartItemIds: string[];
  userId: string;
}

export interface ValidateCartItemsResponse {
  cartItems: CartItemResponse[];
}

/** ==================== GetManyCartItems ====================// */
export interface GetManyCartItemsRequest {
  processId?: string | undefined;
  userId: string;
  page: number;
  limit: number;
}

export interface ShopCartItems {
  shopId: string;
  cartItems: CartItemResponse[];
}

export interface GetManyCartItemsResponse {
  cartItems: ShopCartItems[];
  page: number;
  limit: number;
  totalItems: number;
  totalPages: number;
}

export const CART_SERVICE_PACKAGE_NAME = "CART_SERVICE";

export interface CartServiceClient {
  addCartItem(request: AddCartItemRequest): Observable<CartResponse>;

  updateCartItem(request: UpdateCartItemRequest): Observable<CartResponse>;

  deleteCartItem(request: DeleteCartItemRequest): Observable<CartResponse>;

  validateCartItems(request: ValidateCartItemsRequest): Observable<ValidateCartItemsResponse>;

  getManyCartItems(request: GetManyCartItemsRequest): Observable<GetManyCartItemsResponse>;
}

export interface CartServiceController {
  addCartItem(request: AddCartItemRequest): Promise<CartResponse> | Observable<CartResponse> | CartResponse;

  updateCartItem(request: UpdateCartItemRequest): Promise<CartResponse> | Observable<CartResponse> | CartResponse;

  deleteCartItem(request: DeleteCartItemRequest): Promise<CartResponse> | Observable<CartResponse> | CartResponse;

  validateCartItems(
    request: ValidateCartItemsRequest,
  ): Promise<ValidateCartItemsResponse> | Observable<ValidateCartItemsResponse> | ValidateCartItemsResponse;

  getManyCartItems(
    request: GetManyCartItemsRequest,
  ): Promise<GetManyCartItemsResponse> | Observable<GetManyCartItemsResponse> | GetManyCartItemsResponse;
}

export function CartServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      "addCartItem",
      "updateCartItem",
      "deleteCartItem",
      "validateCartItems",
      "getManyCartItems",
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("CartService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("CartService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const CART_SERVICE_NAME = "CartService";
