// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               v7.34.1
// source: catalog.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "CATALOG_SERVICE";

/** ==================== GetManyProductsRequest ====================// */
export interface GetManyProductsRequest {
  processId?: string | undefined;
  page: number;
  limit: number;
  name?: string | undefined;
  shopId?: string | undefined;
  isApproved?: boolean | undefined;
}

/** ==================== GetManyProductsResponse ====================// */
export interface GetManyProductsResponse {
  page: number;
  limit: number;
  totalItems: number;
  totalPages: number;
  products: ProductResponse[];
}

/** ==================== GetProductRequest ====================// */
export interface GetProductRequest {
  processId?: string | undefined;
  id: string;
}

export interface CreateProductRequest {
  processId?: string | undefined;
  name: string;
  basePrice: number;
  virtualPrice: number;
  brandId?: string | undefined;
  images: string[];
  variants: Variant[];
  createdById?: string | undefined;
  updatedById?: string | undefined;
  shopId: string;
  description: string;
  sizeGuide?: string | undefined;
  provinceId: number;
  provinceName: string;
  districtId: number;
  districtName: string;
  wardId: number;
  wardName: string;
  status: string;
  categories: string[];
  skus: SKUInput[];
  attributes: AttributeProduct[];
}

/** ==================== UpdateProductRequest ====================// */
export interface UpdateProductRequest {
  processId?: string | undefined;
  name: string;
  basePrice: number;
  virtualPrice: number;
  brandId?: string | undefined;
  images: string[];
  variants: Variant[];
  createdById?: string | undefined;
  updatedById?: string | undefined;
  shopId: string;
  description: string;
  sizeGuide?: string | undefined;
  provinceId?: number | undefined;
  provinceName?: string | undefined;
  districtId?: number | undefined;
  districtName?: string | undefined;
  wardId?: number | undefined;
  wardName?: string | undefined;
  status: string;
  categories: string[];
  skus: SKUInput[];
  attributes: AttributeProduct[];
  id: string;
  isApproved?: boolean | undefined;
}

/** ==================== DeleteProductRequest ====================// */
export interface DeleteProductRequest {
  processId?: string | undefined;
  id: string;
  deletedById?: string | undefined;
  shopId: string;
}

/** ==================== ProductResponse ====================// */
export interface ProductResponse {
  id: string;
  name: string;
  description: string;
  provinceId: number;
  districtId: number;
  wardId: number;
  sizeGuide?: string | undefined;
  basePrice: number;
  virtualPrice: number;
  status: string;
  brandId: string;
  images: string[];
  variants: Variant[];
  reviewIds: string[];
  shopId: string;
  likeCount: number;
  ratingCount: number;
  ratingSum: number;
  averageRate: number;
  attributes: AttributeProduct[];
  soldCount: number;
  viewCount: number;
  isApproved: boolean;
  isHidden: boolean;
  totalStock: number;
  skus: SKU[];
  brand: BrandInfo | undefined;
  categories: CategoryInfo[];
  createdById: string;
  updatedById: string;
  deletedById: string;
  deletedAt: string;
  createdAt: string;
  updatedAt: string;
}

export interface ParentCategoryResponse {
  id: string;
  name: string;
}

/** ==================== GetManyCategoriesRequest ====================// */
export interface GetManyCategoriesRequest {
  processId?: string | undefined;
  page: number;
  limit: number;
  name?: string | undefined;
}

/** ==================== GetManyCategoriesResponse ====================// */
export interface GetManyCategoriesResponse {
  page: number;
  limit: number;
  totalItems: number;
  totalPages: number;
  categories: CategoryResponse[];
}

/** ==================== GetCategoryRequest ====================// */
export interface GetCategoryRequest {
  processId?: string | undefined;
  id: string;
}

export interface CategoryResponse {
  id: string;
  name: string;
  logo: string;
  parentCategoryId: string;
  createdById: string;
  updatedById: string;
  deletedById: string;
  deletedAt: string;
  createdAt: string;
  updatedAt: string;
  parentCategory?: ParentCategoryResponse | undefined;
}

export interface CreateCategoryRequest {
  processId?: string | undefined;
  name: string;
  logo: string;
  parentCategoryId?: string | undefined;
  createdById?: string | undefined;
}

export interface UpdateCategoryRequest {
  processId?: string | undefined;
  id: string;
  name?: string | undefined;
  logo?: string | undefined;
  parentCategoryId?: string | undefined;
  updatedById?: string | undefined;
}

export interface DeleteCategoryRequest {
  processId?: string | undefined;
  id: string;
  deletedById?: string | undefined;
}

export interface BrandResponse {
  id: string;
  name: string;
  logo: string;
  createdById: string;
  updatedById: string;
  deletedById: string;
  deletedAt: string;
  createdAt: string;
  updatedAt: string;
}

/** ==================== GetManyBrandsRequest ====================// */
export interface GetManyBrandsRequest {
  processId?: string | undefined;
  page: number;
  limit: number;
  name?: string | undefined;
}

/** ==================== GetManyBrandsResponse ====================// */
export interface GetManyBrandsResponse {
  page: number;
  limit: number;
  totalItems: number;
  totalPages: number;
  brands: BrandResponse[];
}

/** ==================== GetBrandRequest ====================// */
export interface GetBrandRequest {
  processId?: string | undefined;
  id: string;
}

export interface CreateBrandRequest {
  processId?: string | undefined;
  name: string;
  logo: string;
  createdById?: string | undefined;
}

export interface UpdateBrandRequest {
  processId?: string | undefined;
  id: string;
  name?: string | undefined;
  logo?: string | undefined;
  updatedById?: string | undefined;
}

export interface DeleteBrandRequest {
  processId?: string | undefined;
  id: string;
  deletedById?: string | undefined;
}

export interface AttributeCategory {
  isRequired: boolean;
  category: Category | undefined;
}

export interface Category {
  id: string;
  name: string;
  logo: string;
  parentCategoryId: string;
}

export interface AttributeResponse {
  id: string;
  name: string;
  url: string;
  createdById: string;
  updatedById: string;
  deletedById: string;
  deletedAt: string;
  createdAt: string;
  updatedAt: string;
}

/** ==================== GetManyAttributesRequest ====================// */
export interface GetManyAttributesRequest {
  processId?: string | undefined;
  page: number;
  limit: number;
  name?: string | undefined;
}

/** ==================== GetManyAttributesResponse ====================// */
export interface GetManyAttributesResponse {
  page: number;
  limit: number;
  totalItems: number;
  totalPages: number;
  attributes: AttributeResponse[];
}

/** ==================== GetAttributeRequest ====================// */
export interface GetAttributeRequest {
  processId?: string | undefined;
  id: string;
}

export interface CreateAttributeRequest {
  processId?: string | undefined;
  name: string;
  createdById?: string | undefined;
  url?: string | undefined;
}

export interface UpdateAttributeRequest {
  processId?: string | undefined;
  id: string;
  name: string;
  updatedById?: string | undefined;
  url?: string | undefined;
}

export interface DeleteAttributeRequest {
  processId?: string | undefined;
  id: string;
  deletedById?: string | undefined;
}

/** ======================================== Product =========================================// */
export interface Variant {
  value: string;
  options: string[];
}

export interface AttributeProduct {
  name: string;
  value: string;
}

export interface SKU {
  id: string;
  value: string;
  price: number;
  stock: number;
  image: string;
}

export interface SKUInput {
  value: string;
  price: number;
  stock: number;
  image?: string | undefined;
}

export interface BrandInfo {
  id: string;
  name: string;
  logo: string;
}

export interface CategoryInfo {
  id: string;
  name: string;
  logo: string;
  parentCategoryId: string;
}

/**
 * ====================================================== SKU ======================================//
 * ==================== GetSKURequest ====================//
 */
export interface GetSKURequest {
  processId?: string | undefined;
  id: string;
}

/** ==================== SKUResponse ====================// */
export interface SKUResponse {
  id: string;
  value: string;
  price: number;
  stock: number;
  productId: string;
  image: string;
  product: ProductResponse | undefined;
  createdById: string;
  updatedById: string;
  deletedById: string;
  deletedAt: string;
  createdAt: string;
  updatedAt: string;
}

/** ==================== ValidateProductsRequest ====================// */
export interface ValidateItems {
  productId: string;
  skuId: string;
  quantity: number;
  cartItemId: string;
}

export interface ValidateProductsRequest {
  processId?: string | undefined;
  productIds: ValidateItems[];
}

/** ==================== ValidateProductsResponse ====================// */
export interface ValidateItemsResponse {
  productId: string;
  skuId: string;
  cartItemId: string;
  quantity: number;
  isValid: boolean;
  price: number;
  productName: string;
  productImage: string;
  skuValue: string;
  shopId: string;
  error: string;
}

export interface ValidateProductsResponse {
  isValid: boolean;
  items: ValidateItemsResponse[];
}

/** ==================== DashboardSellerRequest ====================// */
export interface DashboardSellerRequest {
  processId?: string | undefined;
  shopId: string;
}

/** ==================== DashboardSellerResponse ====================// */
export interface DashboardSellerResponse {
  totalProducts: number;
}

export const CATALOG_SERVICE_PACKAGE_NAME = "CATALOG_SERVICE";

export interface ProductModuleClient {
  getManyProducts(request: GetManyProductsRequest): Observable<GetManyProductsResponse>;

  getProduct(request: GetProductRequest): Observable<ProductResponse>;

  createProduct(request: CreateProductRequest): Observable<ProductResponse>;

  updateProduct(request: UpdateProductRequest): Observable<ProductResponse>;

  deleteProduct(request: DeleteProductRequest): Observable<ProductResponse>;
}

export interface ProductModuleController {
  getManyProducts(
    request: GetManyProductsRequest,
  ): Promise<GetManyProductsResponse> | Observable<GetManyProductsResponse> | GetManyProductsResponse;

  getProduct(request: GetProductRequest): Promise<ProductResponse> | Observable<ProductResponse> | ProductResponse;

  createProduct(
    request: CreateProductRequest,
  ): Promise<ProductResponse> | Observable<ProductResponse> | ProductResponse;

  updateProduct(
    request: UpdateProductRequest,
  ): Promise<ProductResponse> | Observable<ProductResponse> | ProductResponse;

  deleteProduct(
    request: DeleteProductRequest,
  ): Promise<ProductResponse> | Observable<ProductResponse> | ProductResponse;
}

export function ProductModuleControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["getManyProducts", "getProduct", "createProduct", "updateProduct", "deleteProduct"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("ProductModule", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("ProductModule", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const PRODUCT_MODULE_SERVICE_NAME = "ProductModule";

export interface CategoryModuleClient {
  getManyCategories(request: GetManyCategoriesRequest): Observable<GetManyCategoriesResponse>;

  getCategory(request: GetCategoryRequest): Observable<CategoryResponse>;

  createCategory(request: CreateCategoryRequest): Observable<CategoryResponse>;

  updateCategory(request: UpdateCategoryRequest): Observable<CategoryResponse>;

  deleteCategory(request: DeleteCategoryRequest): Observable<CategoryResponse>;
}

export interface CategoryModuleController {
  getManyCategories(
    request: GetManyCategoriesRequest,
  ): Promise<GetManyCategoriesResponse> | Observable<GetManyCategoriesResponse> | GetManyCategoriesResponse;

  getCategory(request: GetCategoryRequest): Promise<CategoryResponse> | Observable<CategoryResponse> | CategoryResponse;

  createCategory(
    request: CreateCategoryRequest,
  ): Promise<CategoryResponse> | Observable<CategoryResponse> | CategoryResponse;

  updateCategory(
    request: UpdateCategoryRequest,
  ): Promise<CategoryResponse> | Observable<CategoryResponse> | CategoryResponse;

  deleteCategory(
    request: DeleteCategoryRequest,
  ): Promise<CategoryResponse> | Observable<CategoryResponse> | CategoryResponse;
}

export function CategoryModuleControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      "getManyCategories",
      "getCategory",
      "createCategory",
      "updateCategory",
      "deleteCategory",
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("CategoryModule", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("CategoryModule", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const CATEGORY_MODULE_SERVICE_NAME = "CategoryModule";

export interface BrandModuleClient {
  getManyBrands(request: GetManyBrandsRequest): Observable<GetManyBrandsResponse>;

  getBrand(request: GetBrandRequest): Observable<BrandResponse>;

  createBrand(request: CreateBrandRequest): Observable<BrandResponse>;

  updateBrand(request: UpdateBrandRequest): Observable<BrandResponse>;

  deleteBrand(request: DeleteBrandRequest): Observable<BrandResponse>;
}

export interface BrandModuleController {
  getManyBrands(
    request: GetManyBrandsRequest,
  ): Promise<GetManyBrandsResponse> | Observable<GetManyBrandsResponse> | GetManyBrandsResponse;

  getBrand(request: GetBrandRequest): Promise<BrandResponse> | Observable<BrandResponse> | BrandResponse;

  createBrand(request: CreateBrandRequest): Promise<BrandResponse> | Observable<BrandResponse> | BrandResponse;

  updateBrand(request: UpdateBrandRequest): Promise<BrandResponse> | Observable<BrandResponse> | BrandResponse;

  deleteBrand(request: DeleteBrandRequest): Promise<BrandResponse> | Observable<BrandResponse> | BrandResponse;
}

export function BrandModuleControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["getManyBrands", "getBrand", "createBrand", "updateBrand", "deleteBrand"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("BrandModule", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("BrandModule", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const BRAND_MODULE_SERVICE_NAME = "BrandModule";

export interface AttributeModuleClient {
  getManyAttributes(request: GetManyAttributesRequest): Observable<GetManyAttributesResponse>;

  getAttribute(request: GetAttributeRequest): Observable<AttributeResponse>;

  createAttribute(request: CreateAttributeRequest): Observable<AttributeResponse>;

  updateAttribute(request: UpdateAttributeRequest): Observable<AttributeResponse>;

  deleteAttribute(request: DeleteAttributeRequest): Observable<AttributeResponse>;
}

export interface AttributeModuleController {
  getManyAttributes(
    request: GetManyAttributesRequest,
  ): Promise<GetManyAttributesResponse> | Observable<GetManyAttributesResponse> | GetManyAttributesResponse;

  getAttribute(
    request: GetAttributeRequest,
  ): Promise<AttributeResponse> | Observable<AttributeResponse> | AttributeResponse;

  createAttribute(
    request: CreateAttributeRequest,
  ): Promise<AttributeResponse> | Observable<AttributeResponse> | AttributeResponse;

  updateAttribute(
    request: UpdateAttributeRequest,
  ): Promise<AttributeResponse> | Observable<AttributeResponse> | AttributeResponse;

  deleteAttribute(
    request: DeleteAttributeRequest,
  ): Promise<AttributeResponse> | Observable<AttributeResponse> | AttributeResponse;
}

export function AttributeModuleControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      "getManyAttributes",
      "getAttribute",
      "createAttribute",
      "updateAttribute",
      "deleteAttribute",
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("AttributeModule", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("AttributeModule", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const ATTRIBUTE_MODULE_SERVICE_NAME = "AttributeModule";
