// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.8.3
//   protoc               v6.33.5
// source: chat.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "CHAT_SERVICE";

export interface Participant {
  id: string;
  username: string;
  avatar: string;
}

export interface ReadStatusItem {
  isRead: boolean;
  lastSeenMessageId: string;
  deletedAt: string;
}

export interface ConversationResponse {
  id: string;
  participantIds: string[];
  lastMessageId?: string | undefined;
  lastMessageContent?: string | undefined;
  lastMessageAt?: string | undefined;
  lastSenderId?: string | undefined;
  readStatus: { [key: string]: ReadStatusItem };
  createdAt: string;
  updatedAt: string;
  participants: Participant[];
}

export interface ConversationResponse_ReadStatusEntry {
  key: string;
  value: ReadStatusItem | undefined;
}

/** ============================== CreateConversation ================================= // */
export interface CreateConversationRequest {
  processId?: string | undefined;
  participantIds: string[];
}

/** ============================== GetManyConversations ================================= // */
export interface GetManyConversationsRequest {
  processId?: string | undefined;
  page: number;
  limit: number;
  userId: string;
}

export interface ConversationItem {
  id: string;
  participantIds: string[];
  lastMessageId?: string | undefined;
  lastMessageContent?: string | undefined;
  lastMessageAt?: string | undefined;
  lastSenderId?: string | undefined;
  readStatus: { [key: string]: ReadStatusItem };
  participants: Participant[];
}

export interface ConversationItem_ReadStatusEntry {
  key: string;
  value: ReadStatusItem | undefined;
}

export interface GetManyConversationsResponse {
  conversations: ConversationItem[];
  page: number;
  limit: number;
  totalItems: number;
  totalPages: number;
}

export interface MessageResponse {
  id: string;
  conversationId: string;
  senderId: string;
  content: string;
  type: string;
  metadata: string;
  createdAt: string;
}

export interface CreateMessageRequest {
  processId?: string | undefined;
  conversationId: string;
  senderId: string;
  content: string;
  type: string;
  metadata: string;
}

export interface GetManyMessagesRequest {
  processId?: string | undefined;
  page: number;
  limit: number;
  conversationId: string;
  senderId: string;
}

export interface GetManyMessagesResponse {
  messages: MessageResponse[];
  page: number;
  limit: number;
  totalItems: number;
  totalPages: number;
}

export const CHAT_SERVICE_PACKAGE_NAME = "CHAT_SERVICE";

export interface ChatServiceClient {
  createConversation(request: CreateConversationRequest): Observable<ConversationResponse>;

  getManyConversations(request: GetManyConversationsRequest): Observable<GetManyConversationsResponse>;

  createMessage(request: CreateMessageRequest): Observable<MessageResponse>;

  getManyMessages(request: GetManyMessagesRequest): Observable<GetManyMessagesResponse>;
}

export interface ChatServiceController {
  createConversation(
    request: CreateConversationRequest,
  ): Promise<ConversationResponse> | Observable<ConversationResponse> | ConversationResponse;

  getManyConversations(
    request: GetManyConversationsRequest,
  ): Promise<GetManyConversationsResponse> | Observable<GetManyConversationsResponse> | GetManyConversationsResponse;

  createMessage(
    request: CreateMessageRequest,
  ): Promise<MessageResponse> | Observable<MessageResponse> | MessageResponse;

  getManyMessages(
    request: GetManyMessagesRequest,
  ): Promise<GetManyMessagesResponse> | Observable<GetManyMessagesResponse> | GetManyMessagesResponse;
}

export function ChatServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["createConversation", "getManyConversations", "createMessage", "getManyMessages"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("ChatService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("ChatService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const CHAT_SERVICE_NAME = "ChatService";
