// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               v7.34.1
// source: iam.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "IAM_SERVICE";

export interface ExchangeCodeRequest {
  processId?: string | undefined;
  code: string;
}

export interface RefreshSessionRequest {
  processId?: string | undefined;
  refreshToken: string;
}

export interface LogoutCurrentSessionRequest {
  processId?: string | undefined;
  refreshToken: string;
}

export interface ChangePasswordRequest {
  processId?: string | undefined;
  previousPassword: string;
  proposedPassword: string;
  accessToken: string;
}

export interface ValidateTokenRequest {
  processId?: string | undefined;
  accessToken: string;
}

export interface ExchangeCodeResponse {
  accessToken: string;
  idToken: string;
  refreshToken: string;
  expiresIn: number;
  tokenType: string;
  scope: string;
}

export interface Empty {
}

export interface Message {
  message: string;
}

export interface ValidateTokenResponse {
  userId: string;
  username: string;
  groups: string;
  permissions: Permissions[];
  isValid: boolean;
}

export interface Permissions {
  id: string;
  path: string;
  method: string;
  group: string;
}

export interface GetManyPermissionsRequest {
  processId?: string | undefined;
  page: number;
  limit: number;
  group?: string | undefined;
}

export interface GetAllPermissionsRequest {
  processId?: string | undefined;
  group: string;
}

export interface GetAllPermissionsResponse {
  permissions: Permissions[];
}

export interface CreatePermissionResponse {
  id: string;
  name: string;
  description?: string | undefined;
  module: string;
  path: string;
  method: string;
  group: string;
  createdById: string;
  updatedById: string;
  deletedById: string;
  deletedAt: string;
  createdAt: string;
  updatedAt: string;
}

export interface GetManyPermissionsResponse {
  permissions: Permissions[];
  page: number;
  limit: number;
  totalItems: number;
  totalPages: number;
}

export interface CreatePermissionRequest {
  processId?: string | undefined;
  name: string;
  description?: string | undefined;
  module: string;
  path: string;
  method: string;
  group: string;
  createdById?: string | undefined;
}

export interface CreateManyPermissionsRequest {
  permissions: CreatePermissionRequest[];
}

export interface DeleteManyPermissionsRequest {
  ids: string[];
}

export interface CountResponse {
  count: number;
}

export interface GetManyAddressesRequest {
  processId?: string | undefined;
  userId: string;
  page: number;
  limit: number;
}

export interface GetManyAddressesResponse {
  addresses: AddressResponse[];
  page: number;
  limit: number;
  totalItems: number;
  totalPages: number;
}

export interface GetAddressRequest {
  processId?: string | undefined;
  id: string;
  userId: string;
}

export interface CreateAddressRequest {
  processId?: string | undefined;
  userId: string;
  name: string;
  address: string;
  ward?: string | undefined;
  district?: string | undefined;
  province?: string | undefined;
}

export interface UpdateAddressRequest {
  processId?: string | undefined;
  id: string;
  userId?: string | undefined;
  name?: string | undefined;
  address?: string | undefined;
  ward?: string | undefined;
  district?: string | undefined;
  province?: string | undefined;
}

export interface DeleteAddressRequest {
  processId?: string | undefined;
  id: string;
  userId: string;
}

export interface AddressResponse {
  id: string;
  userId: string;
  name: string;
  address: string;
  ward: string;
  district: string;
  province: string;
  createdAt: string;
  updatedAt: string;
}

export interface GetUserRequest {
  processId?: string | undefined;
  id?: string | undefined;
  email?: string | undefined;
  username?: string | undefined;
}

export interface UpdateUserRequest {
  processId?: string | undefined;
  id: string;
  phoneNumber?: string | undefined;
  avatar?: string | undefined;
  gender?: string | undefined;
  birthday?: string | undefined;
}

export interface CreateUserRequest {
  processId?: string | undefined;
  id: string;
  email: string;
  username: string;
  avatar: string;
  group: string;
}

export interface UserResponse {
  id: string;
  email: string;
  username: string;
  phoneNumber: string;
  avatar: string;
  birthday: string;
  gender: string;
  status: string;
  group: string;
  createdById: string;
  updatedById: string;
  deletedById: string;
  deletedAt: string;
  createdAt: string;
  updatedAt: string;
}

export interface GetManyUsersRequest {
  processId?: string | undefined;
  page: number;
  limit: number;
  email?: string | undefined;
  phoneNumber?: string | undefined;
  username?:
    | string
    | undefined;
  /** "MALE" | "FEMALE" | "OTHER" */
  gender?:
    | string
    | undefined;
  /** "ACTIVE" | "INACTIVE" | "BLOCKED" */
  status?: string | undefined;
  group?: string | undefined;
}

export interface GetManyUsersResponse {
  page: number;
  limit: number;
  totalItems: number;
  totalPages: number;
  users: UserBasicInfo[];
}

export interface UserBasicInfo {
  id: string;
  email: string;
  phoneNumber: string;
  gender: string;
  status: string;
  group: string;
}

export const IAM_SERVICE_PACKAGE_NAME = "IAM_SERVICE";

export interface AuthModuleClient {
  exchangeCode(request: ExchangeCodeRequest): Observable<ExchangeCodeResponse>;

  refreshSession(request: RefreshSessionRequest): Observable<ExchangeCodeResponse>;

  logoutCurrentSession(request: LogoutCurrentSessionRequest): Observable<Empty>;

  changePassword(request: ChangePasswordRequest): Observable<Message>;

  validateToken(request: ValidateTokenRequest): Observable<ValidateTokenResponse>;
}

export interface AuthModuleController {
  exchangeCode(
    request: ExchangeCodeRequest,
  ): Promise<ExchangeCodeResponse> | Observable<ExchangeCodeResponse> | ExchangeCodeResponse;

  refreshSession(
    request: RefreshSessionRequest,
  ): Promise<ExchangeCodeResponse> | Observable<ExchangeCodeResponse> | ExchangeCodeResponse;

  logoutCurrentSession(request: LogoutCurrentSessionRequest): Promise<Empty> | Observable<Empty> | Empty;

  changePassword(request: ChangePasswordRequest): Promise<Message> | Observable<Message> | Message;

  validateToken(
    request: ValidateTokenRequest,
  ): Promise<ValidateTokenResponse> | Observable<ValidateTokenResponse> | ValidateTokenResponse;
}

export function AuthModuleControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      "exchangeCode",
      "refreshSession",
      "logoutCurrentSession",
      "changePassword",
      "validateToken",
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("AuthModule", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("AuthModule", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const AUTH_MODULE_SERVICE_NAME = "AuthModule";

export interface PermissionModuleClient {
  getManyPermissions(request: GetManyPermissionsRequest): Observable<GetManyPermissionsResponse>;

  getAllPermissions(request: GetAllPermissionsRequest): Observable<GetAllPermissionsResponse>;

  createPermission(request: CreatePermissionRequest): Observable<CreatePermissionResponse>;

  createManyPermissions(request: CreateManyPermissionsRequest): Observable<CountResponse>;

  deleteManyPermissions(request: DeleteManyPermissionsRequest): Observable<CountResponse>;
}

export interface PermissionModuleController {
  getManyPermissions(
    request: GetManyPermissionsRequest,
  ): Promise<GetManyPermissionsResponse> | Observable<GetManyPermissionsResponse> | GetManyPermissionsResponse;

  getAllPermissions(
    request: GetAllPermissionsRequest,
  ): Promise<GetAllPermissionsResponse> | Observable<GetAllPermissionsResponse> | GetAllPermissionsResponse;

  createPermission(
    request: CreatePermissionRequest,
  ): Promise<CreatePermissionResponse> | Observable<CreatePermissionResponse> | CreatePermissionResponse;

  createManyPermissions(
    request: CreateManyPermissionsRequest,
  ): Promise<CountResponse> | Observable<CountResponse> | CountResponse;

  deleteManyPermissions(
    request: DeleteManyPermissionsRequest,
  ): Promise<CountResponse> | Observable<CountResponse> | CountResponse;
}

export function PermissionModuleControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      "getManyPermissions",
      "getAllPermissions",
      "createPermission",
      "createManyPermissions",
      "deleteManyPermissions",
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("PermissionModule", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("PermissionModule", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const PERMISSION_MODULE_SERVICE_NAME = "PermissionModule";

export interface AddressModuleClient {
  getManyAddresses(request: GetManyAddressesRequest): Observable<GetManyAddressesResponse>;

  getAddress(request: GetAddressRequest): Observable<AddressResponse>;

  createAddress(request: CreateAddressRequest): Observable<AddressResponse>;

  updateAddress(request: UpdateAddressRequest): Observable<AddressResponse>;

  deleteAddress(request: DeleteAddressRequest): Observable<AddressResponse>;
}

export interface AddressModuleController {
  getManyAddresses(
    request: GetManyAddressesRequest,
  ): Promise<GetManyAddressesResponse> | Observable<GetManyAddressesResponse> | GetManyAddressesResponse;

  getAddress(request: GetAddressRequest): Promise<AddressResponse> | Observable<AddressResponse> | AddressResponse;

  createAddress(
    request: CreateAddressRequest,
  ): Promise<AddressResponse> | Observable<AddressResponse> | AddressResponse;

  updateAddress(
    request: UpdateAddressRequest,
  ): Promise<AddressResponse> | Observable<AddressResponse> | AddressResponse;

  deleteAddress(
    request: DeleteAddressRequest,
  ): Promise<AddressResponse> | Observable<AddressResponse> | AddressResponse;
}

export function AddressModuleControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["getManyAddresses", "getAddress", "createAddress", "updateAddress", "deleteAddress"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("AddressModule", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("AddressModule", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const ADDRESS_MODULE_SERVICE_NAME = "AddressModule";

export interface UserModuleClient {
  getUser(request: GetUserRequest): Observable<UserResponse>;

  getManyUsers(request: GetManyUsersRequest): Observable<GetManyUsersResponse>;

  updateUser(request: UpdateUserRequest): Observable<UserResponse>;

  createUser(request: CreateUserRequest): Observable<UserResponse>;
}

export interface UserModuleController {
  getUser(request: GetUserRequest): Promise<UserResponse> | Observable<UserResponse> | UserResponse;

  getManyUsers(
    request: GetManyUsersRequest,
  ): Promise<GetManyUsersResponse> | Observable<GetManyUsersResponse> | GetManyUsersResponse;

  updateUser(request: UpdateUserRequest): Promise<UserResponse> | Observable<UserResponse> | UserResponse;

  createUser(request: CreateUserRequest): Promise<UserResponse> | Observable<UserResponse> | UserResponse;
}

export function UserModuleControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["getUser", "getManyUsers", "updateUser", "createUser"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("UserModule", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("UserModule", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const USER_MODULE_SERVICE_NAME = "UserModule";
