// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               v7.34.1
// source: notification.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "NOTIFICATION_SERVICE";

/** ==================== GetManyNotificationsRequest ====================// */
export interface GetManyNotificationsRequest {
  processId?: string | undefined;
  page: number;
  limit: number;
  userId: string;
  type?: string | undefined;
}

/** ==================== GetManyNotificationsResponse ====================// */
export interface GetManyNotificationsResponse {
  page: number;
  limit: number;
  totalItems: number;
  totalPages: number;
  notifications: NotificationResponse[];
}

/** ==================== GetNotificationRequest ====================// */
export interface GetNotificationRequest {
  processId?: string | undefined;
  id: string;
  userId: string;
}

/** ==================== Metadata ====================// */
export interface Metadata {
  orderId?: string | undefined;
  articleId?: string | undefined;
}

/** ==================== CreateNotificationRequest ====================// */
export interface CreateNotificationRequest {
  processId?: string | undefined;
  title: string;
  description: string;
  userId: string;
  link?: string | undefined;
  image?: string | undefined;
  type: string;
  metadata?: Metadata | undefined;
  createdById?: string | undefined;
}

/** ==================== ReadNotificationRequest ====================// */
export interface ReadNotificationRequest {
  processId?: string | undefined;
  id: string;
  updatedById?: string | undefined;
}

/** ==================== DeleteNotificationRequest ====================// */
export interface DeleteNotificationRequest {
  processId?: string | undefined;
  id: string;
  deletedById?: string | undefined;
}

/** ==================== NotificationResponse ====================// */
export interface NotificationResponse {
  id: string;
  userId: string;
  type: string;
  title: string;
  description: string;
  link?: string | undefined;
  image?: string | undefined;
  isRead: boolean;
  metadata?: Metadata | undefined;
  createdById: string;
  updatedById: string;
  deletedById: string;
  deletedAt: string;
  createdAt: string;
  updatedAt: string;
}

export const NOTIFICATION_SERVICE_PACKAGE_NAME = "NOTIFICATION_SERVICE";

export interface NotificationServiceClient {
  getManyNotifications(request: GetManyNotificationsRequest): Observable<GetManyNotificationsResponse>;

  getNotification(request: GetNotificationRequest): Observable<NotificationResponse>;

  createNotification(request: CreateNotificationRequest): Observable<NotificationResponse>;

  readNotification(request: ReadNotificationRequest): Observable<NotificationResponse>;

  deleteNotification(request: DeleteNotificationRequest): Observable<NotificationResponse>;
}

export interface NotificationServiceController {
  getManyNotifications(
    request: GetManyNotificationsRequest,
  ): Promise<GetManyNotificationsResponse> | Observable<GetManyNotificationsResponse> | GetManyNotificationsResponse;

  getNotification(
    request: GetNotificationRequest,
  ): Promise<NotificationResponse> | Observable<NotificationResponse> | NotificationResponse;

  createNotification(
    request: CreateNotificationRequest,
  ): Promise<NotificationResponse> | Observable<NotificationResponse> | NotificationResponse;

  readNotification(
    request: ReadNotificationRequest,
  ): Promise<NotificationResponse> | Observable<NotificationResponse> | NotificationResponse;

  deleteNotification(
    request: DeleteNotificationRequest,
  ): Promise<NotificationResponse> | Observable<NotificationResponse> | NotificationResponse;
}

export function NotificationServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      "getManyNotifications",
      "getNotification",
      "createNotification",
      "readNotification",
      "deleteNotification",
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("NotificationService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("NotificationService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const NOTIFICATION_SERVICE_NAME = "NotificationService";
