// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.8.3
//   protoc               v6.33.5
// source: order.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "ORDER_SERVICE";

export interface CreateOrderRequest {
  processId?: string | undefined;
  userId: string;
  shippingFee: number;
  discountCode?: string | undefined;
  paymentMethod: string;
  receiver: Receiver | undefined;
  orders: OrderGroup[];
}

export interface Receiver {
  name: string;
  phone: string;
  address: string;
}

export interface OrderGroup {
  shopId: string;
  cartItemIds: string[];
}

export interface CreateOrderResponse {
  orders: Order[];
}

export interface OrderItem {
  id: string;
  orderId: string;
  productId: string;
  skuId: string;
  shopId: string;
  productName: string;
  skuValue: string;
  quantity: number;
  price: number;
  total: number;
  productImage: string;
  createdAt: string;
  updatedAt: string;
}

export interface Timeline {
  status: string;
  at: string;
}

export interface Order {
  id: string;
  code: string;
  userId: string;
  shopId: string;
  status: string;
  itemTotal: number;
  shippingFee: number;
  discount: number;
  grandTotal: number;
  receiver: Receiver | undefined;
  paymentMethod: string;
  paymentStatus: string;
  paymentId: string;
  timeline: Timeline[];
  items: OrderItem[];
  createdById?: string | undefined;
  updatedById?: string | undefined;
  deletedById?: string | undefined;
  deletedAt?: string | undefined;
  createdAt: string;
  updatedAt: string;
}

/** ================================= Update status order =================================== */
export interface UpdateStatusOrderRequest {
  processId?: string | undefined;
  id: string;
  userId?: string | undefined;
  shopId?: string | undefined;
  status: string;
}

/** ================================= Cancel order =================================== */
export interface CancelOrderRequest {
  processId?: string | undefined;
  orderId: string;
  userId?: string | undefined;
  shopId?: string | undefined;
}

/** ================================= Dashboard seller =================================== */
export interface DashboardSellerRequest {
  processId?: string | undefined;
  userId: string;
  shopId: string;
}

export interface DashboardSellerResponse {
  totalOrders: number;
  completedOrders: number;
  pendingOrders: number;
  confirmedOrders: number;
  totalRevenue: number;
}

export const ORDER_SERVICE_PACKAGE_NAME = "ORDER_SERVICE";

export interface OrderServiceClient {
  createOrder(request: CreateOrderRequest): Observable<CreateOrderResponse>;

  updateStatusOrder(request: UpdateStatusOrderRequest): Observable<Order>;

  cancelOrder(request: CancelOrderRequest): Observable<Order>;

  dashboardSeller(request: DashboardSellerRequest): Observable<DashboardSellerResponse>;
}

export interface OrderServiceController {
  createOrder(
    request: CreateOrderRequest,
  ): Promise<CreateOrderResponse> | Observable<CreateOrderResponse> | CreateOrderResponse;

  updateStatusOrder(request: UpdateStatusOrderRequest): Promise<Order> | Observable<Order> | Order;

  cancelOrder(request: CancelOrderRequest): Promise<Order> | Observable<Order> | Order;

  dashboardSeller(
    request: DashboardSellerRequest,
  ): Promise<DashboardSellerResponse> | Observable<DashboardSellerResponse> | DashboardSellerResponse;
}

export function OrderServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["createOrder", "updateStatusOrder", "cancelOrder", "dashboardSeller"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("OrderService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("OrderService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const ORDER_SERVICE_NAME = "OrderService";
