// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               v7.34.1
// source: payment.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "PAYMENT_SERVICE";

/** =========================================== Receiver ===========================================// */
export interface WebhookTransactionRequest {
  id: number;
  gateway: string;
  transactionDate: string;
  accountNumber?: string | undefined;
  code?: string | undefined;
  content?: string | undefined;
  transferType: string;
  transferAmount: number;
  accumulated: number;
  subAccount?: string | undefined;
  referenceCode?: string | undefined;
  description: string;
}

export interface WebhookTransactionResponse {
  message: string;
  paymentCode: string;
  userId: string;
  paymentId: string;
}

/** ==================== GetPayment ====================// */
export interface GetPaymentRequest {
  processId?: string | undefined;
  id: string;
  userId?: string | undefined;
}

/** ==================== CreatePayment ====================// */
export interface CreatePaymentRequest {
  processId?: string | undefined;
  id: string;
  code: string;
  userId: string;
  orderId: string[];
  method: string;
  status: string;
  amount: number;
}

export interface PaymentResponse {
  id: string;
  code: string;
  userId: string;
  orderId: string[];
  method: string;
  status: string;
  amount: number;
  createdById?: string | undefined;
  updatedById?: string | undefined;
  deletedById?: string | undefined;
  deletedAt?: string | undefined;
  createdAt: string;
  updatedAt: string;
  qrCode?: string | undefined;
}

/** ==================== GetManyPayments ====================// */
export interface GetManyPaymentsRequest {
  processId?: string | undefined;
  page: number;
  limit: number;
  createdAt?: string | undefined;
  code?: string | undefined;
  userId?: string | undefined;
  method?: string | undefined;
  status?: string | undefined;
  amount?: number | undefined;
}

/** ==================== GetManyPaymentsResponse ====================// */
export interface GetManyPaymentsResponse {
  payments: PaymentResponse[];
  page: number;
  limit: number;
  totalItems: number;
  totalPages: number;
}

/** ==================== UpdatePaymentStatus ====================// */
export interface UpdatePaymentStatusRequest {
  processId?: string | undefined;
  id: string;
  status: string;
  updatedById?: string | undefined;
}

/** ==================== DashboardPayment ==================== */
export interface DashboardPaymentRequest {
  processId?: string | undefined;
}

export interface DashboardPaymentResponse {
  totalAmount: number;
}

/** ==================== GetRefund ====================// */
export interface GetRefundRequest {
  processId?: string | undefined;
  id: string;
  userId?: string | undefined;
}

/** ==================== CreateRefund ====================// */
export interface CreateRefundRequest {
  processId?: string | undefined;
  userId: string;
  orderId: string;
  amount: number;
  reason?: string | undefined;
  createdById?: string | undefined;
}

export interface RefundResponse {
  id: string;
  userId: string;
  orderId: string;
  amount: number;
  status: string;
  reason?: string | undefined;
  createdById?: string | undefined;
  updatedById?: string | undefined;
  deletedById?: string | undefined;
  deletedAt?: string | undefined;
  createdAt: string;
  updatedAt: string;
}

/** ==================== GetManyRefunds ====================// */
export interface GetManyRefundsRequest {
  processId?: string | undefined;
  page: number;
  limit: number;
  userId?: string | undefined;
  orderId?: string | undefined;
  status?: string | undefined;
}

export interface GetManyRefundsResponse {
  refunds: RefundResponse[];
  page: number;
  limit: number;
  totalItems: number;
  totalPages: number;
}

/** ==================== UpdateRefundStatus ====================// */
export interface UpdateRefundStatusRequest {
  processId?: string | undefined;
  id: string;
  status: string;
  updatedById?: string | undefined;
}

export const PAYMENT_SERVICE_PACKAGE_NAME = "PAYMENT_SERVICE";

export interface PaymentModuleClient {
  getManyPayments(request: GetManyPaymentsRequest): Observable<GetManyPaymentsResponse>;

  getPayment(request: GetPaymentRequest): Observable<PaymentResponse>;

  createPayment(request: CreatePaymentRequest): Observable<PaymentResponse>;

  updatePaymentStatus(request: UpdatePaymentStatusRequest): Observable<PaymentResponse>;

  dashboardPayment(request: DashboardPaymentRequest): Observable<DashboardPaymentResponse>;
}

export interface PaymentModuleController {
  getManyPayments(
    request: GetManyPaymentsRequest,
  ): Promise<GetManyPaymentsResponse> | Observable<GetManyPaymentsResponse> | GetManyPaymentsResponse;

  getPayment(request: GetPaymentRequest): Promise<PaymentResponse> | Observable<PaymentResponse> | PaymentResponse;

  createPayment(
    request: CreatePaymentRequest,
  ): Promise<PaymentResponse> | Observable<PaymentResponse> | PaymentResponse;

  updatePaymentStatus(
    request: UpdatePaymentStatusRequest,
  ): Promise<PaymentResponse> | Observable<PaymentResponse> | PaymentResponse;

  dashboardPayment(
    request: DashboardPaymentRequest,
  ): Promise<DashboardPaymentResponse> | Observable<DashboardPaymentResponse> | DashboardPaymentResponse;
}

export function PaymentModuleControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      "getManyPayments",
      "getPayment",
      "createPayment",
      "updatePaymentStatus",
      "dashboardPayment",
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("PaymentModule", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("PaymentModule", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const PAYMENT_MODULE_SERVICE_NAME = "PaymentModule";

export interface TransactionModuleClient {
  receiver(request: WebhookTransactionRequest): Observable<WebhookTransactionResponse>;
}

export interface TransactionModuleController {
  receiver(
    request: WebhookTransactionRequest,
  ): Promise<WebhookTransactionResponse> | Observable<WebhookTransactionResponse> | WebhookTransactionResponse;
}

export function TransactionModuleControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["receiver"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("TransactionModule", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("TransactionModule", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const TRANSACTION_MODULE_SERVICE_NAME = "TransactionModule";

export interface RefundModuleClient {
  getManyRefunds(request: GetManyRefundsRequest): Observable<GetManyRefundsResponse>;

  getRefund(request: GetRefundRequest): Observable<RefundResponse>;

  createRefund(request: CreateRefundRequest): Observable<RefundResponse>;

  updateRefundStatus(request: UpdateRefundStatusRequest): Observable<RefundResponse>;
}

export interface RefundModuleController {
  getManyRefunds(
    request: GetManyRefundsRequest,
  ): Promise<GetManyRefundsResponse> | Observable<GetManyRefundsResponse> | GetManyRefundsResponse;

  getRefund(request: GetRefundRequest): Promise<RefundResponse> | Observable<RefundResponse> | RefundResponse;

  createRefund(request: CreateRefundRequest): Promise<RefundResponse> | Observable<RefundResponse> | RefundResponse;

  updateRefundStatus(
    request: UpdateRefundStatusRequest,
  ): Promise<RefundResponse> | Observable<RefundResponse> | RefundResponse;
}

export function RefundModuleControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["getManyRefunds", "getRefund", "createRefund", "updateRefundStatus"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("RefundModule", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("RefundModule", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const REFUND_MODULE_SERVICE_NAME = "RefundModule";
