// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.8.3
//   protoc               v6.33.5
// source: payment.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "PAYMENT_SERVICE";

/** =========================================== Receiver ===========================================// */
export interface WebhookTransactionRequest {
  id: number;
  gateway: string;
  transactionDate: string;
  accountNumber?: string | undefined;
  code?: string | undefined;
  content?: string | undefined;
  transferType: string;
  transferAmount: number;
  accumulated: number;
  subAccount?: string | undefined;
  referenceCode?: string | undefined;
  description: string;
}

export interface WebhookTransactionResponse {
  message: string;
  paymentCode: string;
  userId: string;
  paymentId: string;
}

/** ==================== GetPayment ====================// */
export interface GetPaymentRequest {
  processId?: string | undefined;
  id: string;
  userId: string;
}

/** ==================== CreatePayment ====================// */
export interface CreatePaymentRequest {
  processId?: string | undefined;
  id: string;
  code: string;
  userId: string;
  orderId: string[];
  method: string;
  status: string;
  amount: number;
}

export interface PaymentResponse {
  id: string;
  code: string;
  userId: string;
  orderId: string;
  method: string;
  status: string;
  amount: number;
  createdById: string;
  updatedById: string;
  deletedById: string;
  deletedAt: string;
  createdAt: string;
  updatedAt: string;
  qrCode?: string | undefined;
}

/** ==================== GetManyPayments ====================// */
export interface GetManyPaymentsRequest {
  processId?: string | undefined;
  page: number;
  limit: number;
  createdAt?: string | undefined;
  code?: string | undefined;
  userId?: string | undefined;
  method?: string | undefined;
  status?: string | undefined;
  amount?: number | undefined;
}

/** ==================== GetManyPaymentsResponse ====================// */
export interface GetManyPaymentsResponse {
  payments: PaymentResponse[];
  page: number;
  limit: number;
  totalItems: number;
  totalPages: number;
}

/** ==================== UpdatePaymentStatus ====================// */
export interface UpdatePaymentStatusRequest {
  processId?: string | undefined;
  id: string;
  status: string;
  updatedById: string;
}

/** ==================== DashboardPayment ==================== */
export interface DashboardPaymentRequest {
  processId?: string | undefined;
}

export interface DashboardPaymentResponse {
  totalAmount: number;
}

export const PAYMENT_SERVICE_PACKAGE_NAME = "PAYMENT_SERVICE";

export interface PaymentServiceClient {
  receiver(request: WebhookTransactionRequest): Observable<WebhookTransactionResponse>;

  getManyPayments(request: GetManyPaymentsRequest): Observable<GetManyPaymentsResponse>;

  getPayment(request: GetPaymentRequest): Observable<PaymentResponse>;

  createPayment(request: CreatePaymentRequest): Observable<PaymentResponse>;

  updatePaymentStatus(request: UpdatePaymentStatusRequest): Observable<PaymentResponse>;

  dashboardPayment(request: DashboardPaymentRequest): Observable<DashboardPaymentResponse>;
}

export interface PaymentServiceController {
  receiver(
    request: WebhookTransactionRequest,
  ): Promise<WebhookTransactionResponse> | Observable<WebhookTransactionResponse> | WebhookTransactionResponse;

  getManyPayments(
    request: GetManyPaymentsRequest,
  ): Promise<GetManyPaymentsResponse> | Observable<GetManyPaymentsResponse> | GetManyPaymentsResponse;

  getPayment(request: GetPaymentRequest): Promise<PaymentResponse> | Observable<PaymentResponse> | PaymentResponse;

  createPayment(
    request: CreatePaymentRequest,
  ): Promise<PaymentResponse> | Observable<PaymentResponse> | PaymentResponse;

  updatePaymentStatus(
    request: UpdatePaymentStatusRequest,
  ): Promise<PaymentResponse> | Observable<PaymentResponse> | PaymentResponse;

  dashboardPayment(
    request: DashboardPaymentRequest,
  ): Promise<DashboardPaymentResponse> | Observable<DashboardPaymentResponse> | DashboardPaymentResponse;
}

export function PaymentServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      "receiver",
      "getManyPayments",
      "getPayment",
      "createPayment",
      "updatePaymentStatus",
      "dashboardPayment",
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("PaymentService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("PaymentService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const PAYMENT_SERVICE_NAME = "PaymentService";
