// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               v7.34.1
// source: product.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "PRODUCT_SERVICE";

/** ====================================== Category ======================================// */
export interface ParentCategoryResponse {
  id: string;
  name: string;
}

export interface CategoryResponse {
  id: string;
  name: string;
  logo: string;
  parentCategoryId: string;
  createdById: string;
  updatedById: string;
  deletedById: string;
  deletedAt: string;
  createdAt: string;
  updatedAt: string;
  parentCategory?: ParentCategoryResponse | undefined;
}

/** ==================== CreateCategoryRequest ====================// */
export interface CreateCategoryRequest {
  processId?: string | undefined;
  name: string;
  logo: string;
  parentCategoryId?: string | undefined;
  createdById?: string | undefined;
}

/** ==================== UpdateCategoryRequest ====================// */
export interface UpdateCategoryRequest {
  processId?: string | undefined;
  id: string;
  name?: string | undefined;
  logo?: string | undefined;
  parentCategoryId?: string | undefined;
  updatedById?: string | undefined;
}

/** ==================== DeleteCategoryRequest ====================// */
export interface DeleteCategoryRequest {
  processId?: string | undefined;
  id: string;
  deletedById?: string | undefined;
}

/** ========================================== Brand ==========================================// */
export interface BrandResponse {
  id: string;
  name: string;
  logo: string;
  createdById: string;
  updatedById: string;
  deletedById: string;
  deletedAt: string;
  createdAt: string;
  updatedAt: string;
}

/** ==================== CreateBrandRequest ====================// */
export interface CreateBrandRequest {
  processId?: string | undefined;
  name: string;
  logo: string;
  createdById?: string | undefined;
}

/** ==================== UpdateBrandRequest ====================// */
export interface UpdateBrandRequest {
  processId?: string | undefined;
  id: string;
  name?: string | undefined;
  logo?: string | undefined;
  updatedById?: string | undefined;
}

/** ==================== DeleteBrandRequest ====================// */
export interface DeleteBrandRequest {
  processId?: string | undefined;
  id: string;
  deletedById?: string | undefined;
}

/** ======================================== Attribute =========================================// */
export interface AttributeCategory {
  isRequired: boolean;
  category: Category | undefined;
}

export interface Category {
  id: string;
  name: string;
  logo: string;
  parentCategoryId: string;
}

export interface AttributeResponse {
  id: string;
  name: string;
  url: string;
  createdById: string;
  updatedById: string;
  deletedById: string;
  deletedAt: string;
  createdAt: string;
  updatedAt: string;
}

/** ==================== CreateAttributeRequest ====================// */
export interface CreateAttributeRequest {
  processId?: string | undefined;
  name: string;
  createdById?: string | undefined;
  url?: string | undefined;
}

/** ==================== UpdateAttributeRequest ====================// */
export interface UpdateAttributeRequest {
  processId?: string | undefined;
  id: string;
  name: string;
  updatedById?: string | undefined;
  url?: string | undefined;
}

/** ==================== DeleteAttributeRequest ====================// */
export interface DeleteAttributeRequest {
  processId?: string | undefined;
  id: string;
  deletedById?: string | undefined;
}

/** ======================================== Product =========================================// */
export interface Variant {
  value: string;
  options: string[];
}

export interface AttributeProduct {
  name: string;
  value: string;
}

export interface SKU {
  id: string;
  value: string;
  price: number;
  stock: number;
  image: string;
}

export interface SKUInput {
  value: string;
  price: number;
  stock: number;
  image?: string | undefined;
}

/** ==================== CreateProductRequest ====================// */
export interface CreateProductRequest {
  processId?: string | undefined;
  name: string;
  basePrice: number;
  virtualPrice: number;
  brandId?: string | undefined;
  images: string[];
  variants: Variant[];
  createdById?: string | undefined;
  updatedById?: string | undefined;
  shopId: string;
  description: string;
  sizeGuide?: string | undefined;
  provinceId: number;
  provinceName: string;
  districtId: number;
  districtName: string;
  wardId: number;
  wardName: string;
  status: string;
  categories: string[];
  skus: SKUInput[];
  attributes: AttributeProduct[];
}

/** ==================== UpdateProductRequest ====================// */
export interface UpdateProductRequest {
  processId?: string | undefined;
  name: string;
  basePrice: number;
  virtualPrice: number;
  brandId?: string | undefined;
  images: string[];
  variants: Variant[];
  createdById?: string | undefined;
  updatedById?: string | undefined;
  shopId: string;
  description: string;
  sizeGuide?: string | undefined;
  provinceId?: number | undefined;
  provinceName?: string | undefined;
  districtId?: number | undefined;
  districtName?: string | undefined;
  wardId?: number | undefined;
  wardName?: string | undefined;
  status: string;
  categories: string[];
  skus: SKUInput[];
  attributes: AttributeProduct[];
  id: string;
  isApproved?: boolean | undefined;
}

/** ==================== DeleteProductRequest ====================// */
export interface DeleteProductRequest {
  processId?: string | undefined;
  id: string;
  deletedById?: string | undefined;
  shopId: string;
}

/** ==================== ProductResponse ====================// */
export interface ProductResponse {
  id: string;
  name: string;
  description: string;
  provinceId: number;
  districtId: number;
  wardId: number;
  sizeGuide?: string | undefined;
  basePrice: number;
  virtualPrice: number;
  status: string;
  brandId: string;
  images: string[];
  variants: Variant[];
  reviewIds: string[];
  shopId: string;
  likeCount: number;
  ratingCount: number;
  ratingSum: number;
  averageRate: number;
  attributes: AttributeProduct[];
  soldCount: number;
  viewCount: number;
  isApproved: boolean;
  isHidden: boolean;
  totalStock: number;
  skus: SKU[];
  brand: BrandInfo | undefined;
  categories: CategoryInfo[];
  createdById: string;
  updatedById: string;
  deletedById: string;
  deletedAt: string;
  createdAt: string;
  updatedAt: string;
}

export interface BrandInfo {
  id: string;
  name: string;
  logo: string;
}

export interface CategoryInfo {
  id: string;
  name: string;
  logo: string;
  parentCategoryId: string;
}

/**
 * ====================================================== SKU ======================================//
 * ==================== GetSKURequest ====================//
 */
export interface GetSKURequest {
  processId?: string | undefined;
  id: string;
}

/** ==================== SKUResponse ====================// */
export interface SKUResponse {
  id: string;
  value: string;
  price: number;
  stock: number;
  productId: string;
  image: string;
  product: ProductResponse | undefined;
  createdById: string;
  updatedById: string;
  deletedById: string;
  deletedAt: string;
  createdAt: string;
  updatedAt: string;
}

/** ==================== ValidateProductsRequest ====================// */
export interface ValidateItems {
  productId: string;
  skuId: string;
  quantity: number;
  cartItemId: string;
}

export interface ValidateProductsRequest {
  processId?: string | undefined;
  productIds: ValidateItems[];
}

/** ==================== ValidateProductsResponse ====================// */
export interface ValidateItemsResponse {
  productId: string;
  skuId: string;
  cartItemId: string;
  quantity: number;
  isValid: boolean;
  price: number;
  productName: string;
  productImage: string;
  skuValue: string;
  shopId: string;
  error: string;
}

export interface ValidateProductsResponse {
  isValid: boolean;
  items: ValidateItemsResponse[];
}

/** ==================== DashboardSellerRequest ====================// */
export interface DashboardSellerRequest {
  processId?: string | undefined;
  shopId: string;
}

/** ==================== DashboardSellerResponse ====================// */
export interface DashboardSellerResponse {
  totalProducts: number;
}

export const PRODUCT_SERVICE_PACKAGE_NAME = "PRODUCT_SERVICE";

export interface ProductServiceClient {
  createCategory(request: CreateCategoryRequest): Observable<CategoryResponse>;

  updateCategory(request: UpdateCategoryRequest): Observable<CategoryResponse>;

  deleteCategory(request: DeleteCategoryRequest): Observable<CategoryResponse>;

  createBrand(request: CreateBrandRequest): Observable<BrandResponse>;

  updateBrand(request: UpdateBrandRequest): Observable<BrandResponse>;

  deleteBrand(request: DeleteBrandRequest): Observable<BrandResponse>;

  createAttribute(request: CreateAttributeRequest): Observable<AttributeResponse>;

  updateAttribute(request: UpdateAttributeRequest): Observable<AttributeResponse>;

  deleteAttribute(request: DeleteAttributeRequest): Observable<AttributeResponse>;

  createProduct(request: CreateProductRequest): Observable<ProductResponse>;

  updateProduct(request: UpdateProductRequest): Observable<ProductResponse>;

  deleteProduct(request: DeleteProductRequest): Observable<ProductResponse>;

  getSku(request: GetSKURequest): Observable<SKUResponse>;

  validateProducts(request: ValidateProductsRequest): Observable<ValidateProductsResponse>;

  dashboardSeller(request: DashboardSellerRequest): Observable<DashboardSellerResponse>;
}

export interface ProductServiceController {
  createCategory(
    request: CreateCategoryRequest,
  ): Promise<CategoryResponse> | Observable<CategoryResponse> | CategoryResponse;

  updateCategory(
    request: UpdateCategoryRequest,
  ): Promise<CategoryResponse> | Observable<CategoryResponse> | CategoryResponse;

  deleteCategory(
    request: DeleteCategoryRequest,
  ): Promise<CategoryResponse> | Observable<CategoryResponse> | CategoryResponse;

  createBrand(request: CreateBrandRequest): Promise<BrandResponse> | Observable<BrandResponse> | BrandResponse;

  updateBrand(request: UpdateBrandRequest): Promise<BrandResponse> | Observable<BrandResponse> | BrandResponse;

  deleteBrand(request: DeleteBrandRequest): Promise<BrandResponse> | Observable<BrandResponse> | BrandResponse;

  createAttribute(
    request: CreateAttributeRequest,
  ): Promise<AttributeResponse> | Observable<AttributeResponse> | AttributeResponse;

  updateAttribute(
    request: UpdateAttributeRequest,
  ): Promise<AttributeResponse> | Observable<AttributeResponse> | AttributeResponse;

  deleteAttribute(
    request: DeleteAttributeRequest,
  ): Promise<AttributeResponse> | Observable<AttributeResponse> | AttributeResponse;

  createProduct(
    request: CreateProductRequest,
  ): Promise<ProductResponse> | Observable<ProductResponse> | ProductResponse;

  updateProduct(
    request: UpdateProductRequest,
  ): Promise<ProductResponse> | Observable<ProductResponse> | ProductResponse;

  deleteProduct(
    request: DeleteProductRequest,
  ): Promise<ProductResponse> | Observable<ProductResponse> | ProductResponse;

  getSku(request: GetSKURequest): Promise<SKUResponse> | Observable<SKUResponse> | SKUResponse;

  validateProducts(
    request: ValidateProductsRequest,
  ): Promise<ValidateProductsResponse> | Observable<ValidateProductsResponse> | ValidateProductsResponse;

  dashboardSeller(
    request: DashboardSellerRequest,
  ): Promise<DashboardSellerResponse> | Observable<DashboardSellerResponse> | DashboardSellerResponse;
}

export function ProductServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      "createCategory",
      "updateCategory",
      "deleteCategory",
      "createBrand",
      "updateBrand",
      "deleteBrand",
      "createAttribute",
      "updateAttribute",
      "deleteAttribute",
      "createProduct",
      "updateProduct",
      "deleteProduct",
      "getSku",
      "validateProducts",
      "dashboardSeller",
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("ProductService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("ProductService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const PRODUCT_SERVICE_NAME = "ProductService";
