// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               v7.34.1
// source: promotion.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "PROMOTION_SERVICE";

/** Request Messages */
export interface GetManyPromotionsRequest {
  processId?: string | undefined;
  code?: string | undefined;
  name?: string | undefined;
  status?: string | undefined;
  startsAt?: string | undefined;
  endsAt?: string | undefined;
  scope?: string | undefined;
  discountType?: string | undefined;
  page: number;
  limit: number;
  includeUsed?: boolean | undefined;
  userId?: string | undefined;
}

export interface GetPromotionRequest {
  processId?: string | undefined;
  id?: string | undefined;
  code?: string | undefined;
}

export interface CreatePromotionRequest {
  processId?: string | undefined;
  code: string;
  name: string;
  description?: string | undefined;
  status: string;
  startsAt: string;
  endsAt: string;
  scope: string;
  minOrderSubtotal: number;
  discountType: string;
  discountValue: number;
  maxDiscount?: number | undefined;
  totalLimit?: number | undefined;
  createdById: string;
}

export interface UpdatePromotionRequest {
  processId?: string | undefined;
  id: string;
  code?: string | undefined;
  name?: string | undefined;
  description?: string | undefined;
  status?: string | undefined;
  startsAt?: string | undefined;
  endsAt?: string | undefined;
  scope?: string | undefined;
  minOrderSubtotal?: number | undefined;
  discountType?: string | undefined;
  discountValue?: number | undefined;
  maxDiscount?: number | undefined;
  totalLimit?: number | undefined;
  updatedById: string;
}

export interface DeletePromotionRequest {
  id: string;
  deletedById: string;
  processId?: string | undefined;
}

/** Response Messages */
export interface PromotionResponse {
  id: string;
  code: string;
  name: string;
  description?: string | undefined;
  status: string;
  startsAt: string;
  endsAt: string;
  scope: string;
  minOrderSubtotal: number;
  discountType: string;
  discountValue: number;
  maxDiscount?: number | undefined;
  totalLimit?: number | undefined;
  usedCount: number;
  createdById?: string | undefined;
  updatedById?: string | undefined;
  deletedById?: string | undefined;
  deletedAt?: string | undefined;
  createdAt: string;
  updatedAt: string;
}

export interface PromotionListItem {
  id: string;
  code: string;
  name: string;
  startsAt: string;
  endsAt: string;
  status: string;
  scope: string;
  discountType: string;
  totalLimit?: number | undefined;
}

export interface GetManyPromotionsResponse {
  page: number;
  limit: number;
  totalItems: number;
  totalPages: number;
  promotions: PromotionListItem[];
}

/** Check Promotion Request */
export interface CheckPromotionRequest {
  processId?: string | undefined;
  code: string;
  userId: string;
}

export interface ClaimPromotionRequest {
  processId?: string | undefined;
  promotionId: string;
  userId: string;
}

export interface GetMyVouchersRequest {
  processId?: string | undefined;
  userId: string;
  page: number;
  limit: number;
  /**
   * Filter trạng thái: "available" (chưa dùng & chưa huỷ), "used", "cancelled".
   * Bỏ trống → trả tất cả.
   */
  status?: string | undefined;
}

export interface PromotionRedemptionResponse {
  id: string;
  promotionId: string;
  userId: string;
  orderIds: string[];
  code: string;
  discountType: string;
  discountValue: number;
  minOrderSubtotal: number;
  maxDiscount?: number | undefined;
  claimedAt: string;
  usedAt?: string | undefined;
  cancelledAt?: string | undefined;
  createdAt: string;
}

export interface GetMyVouchersResponse {
  page: number;
  limit: number;
  totalItems: number;
  totalPages: number;
  redemptions: PromotionRedemptionResponse[];
}

export const PROMOTION_SERVICE_PACKAGE_NAME = "PROMOTION_SERVICE";

export interface PromotionModuleClient {
  getManyPromotions(request: GetManyPromotionsRequest): Observable<GetManyPromotionsResponse>;

  getPromotion(request: GetPromotionRequest): Observable<PromotionResponse>;

  createPromotion(request: CreatePromotionRequest): Observable<PromotionResponse>;

  updatePromotion(request: UpdatePromotionRequest): Observable<PromotionResponse>;

  deletePromotion(request: DeletePromotionRequest): Observable<PromotionResponse>;

  checkPromotion(request: CheckPromotionRequest): Observable<PromotionResponse>;
}

export interface PromotionModuleController {
  getManyPromotions(
    request: GetManyPromotionsRequest,
  ): Promise<GetManyPromotionsResponse> | Observable<GetManyPromotionsResponse> | GetManyPromotionsResponse;

  getPromotion(
    request: GetPromotionRequest,
  ): Promise<PromotionResponse> | Observable<PromotionResponse> | PromotionResponse;

  createPromotion(
    request: CreatePromotionRequest,
  ): Promise<PromotionResponse> | Observable<PromotionResponse> | PromotionResponse;

  updatePromotion(
    request: UpdatePromotionRequest,
  ): Promise<PromotionResponse> | Observable<PromotionResponse> | PromotionResponse;

  deletePromotion(
    request: DeletePromotionRequest,
  ): Promise<PromotionResponse> | Observable<PromotionResponse> | PromotionResponse;

  checkPromotion(
    request: CheckPromotionRequest,
  ): Promise<PromotionResponse> | Observable<PromotionResponse> | PromotionResponse;
}

export function PromotionModuleControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      "getManyPromotions",
      "getPromotion",
      "createPromotion",
      "updatePromotion",
      "deletePromotion",
      "checkPromotion",
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("PromotionModule", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("PromotionModule", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const PROMOTION_MODULE_SERVICE_NAME = "PromotionModule";

export interface RedemptionModuleClient {
  claimPromotion(request: ClaimPromotionRequest): Observable<PromotionRedemptionResponse>;

  getMyVouchers(request: GetMyVouchersRequest): Observable<GetMyVouchersResponse>;
}

export interface RedemptionModuleController {
  claimPromotion(
    request: ClaimPromotionRequest,
  ): Promise<PromotionRedemptionResponse> | Observable<PromotionRedemptionResponse> | PromotionRedemptionResponse;

  getMyVouchers(
    request: GetMyVouchersRequest,
  ): Promise<GetMyVouchersResponse> | Observable<GetMyVouchersResponse> | GetMyVouchersResponse;
}

export function RedemptionModuleControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["claimPromotion", "getMyVouchers"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("RedemptionModule", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("RedemptionModule", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const REDEMPTION_MODULE_SERVICE_NAME = "RedemptionModule";
