// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.8.3
//   protoc               v6.33.5
// source: query.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "QUERY_SERVICE";

/** ====================================== Category ======================================// */
export interface CategoryProduct {
  id: string;
  name: string;
  logo: string;
  parentCategoryId?: string | undefined;
}

/** ==================== GetCategoryRequest ====================// */
export interface GetCategoryRequest {
  processId?: string | undefined;
  id: string;
}

export interface GetCategoryResponse {
  id: string;
  name: string;
  logo: string;
  parentId?: string | undefined;
  path: string;
  level: number;
  createdAt: string;
  updatedAt: string;
}

/** ==================== GetManyCategoriesRequest ====================// */
export interface GetManyCategoriesRequest {
  processId?: string | undefined;
  parentCategoryId?: string | undefined;
}

export interface GetManyCategoriesResponse {
  categories: GetCategoryResponse[];
}

/**
 * ====================================== Brand ======================================//
 * ==================== GetBrandRequest ====================//
 */
export interface GetBrandRequest {
  processId?: string | undefined;
  id: string;
}

export interface GetBrandResponse {
  id: string;
  name: string;
  logo: string;
  productsCount: number;
  soldCount: number;
  categoryIds: string[];
  categories: CategoryProduct[];
  createdAt: string;
  updatedAt: string;
}

/** ==================== GetManyBrandsRequest ====================// */
export interface GetManyBrandsRequest {
  processId?: string | undefined;
  page: number;
  limit: number;
  name?: string | undefined;
}

export interface GetManyBrandsResponse {
  brands: GetBrandResponse[];
  page: number;
  limit: number;
  totalItems: number;
  totalPages: number;
}

/**
 * ====================================== Attribute ======================================//
 * ==================== GetAttributeRequest ====================//
 */
export interface GetAttributeRequest {
  processId?: string | undefined;
  id: string;
}

export interface GetAttributeResponse {
  id: string;
  name: string;
  categoryIds: string[];
  categories: CategoryProduct[];
  createdAt: string;
  updatedAt: string;
}

/** ==================== GetManyAttributesRequest ====================// */
export interface GetManyAttributesRequest {
  processId?: string | undefined;
  page: number;
  limit: number;
  name?: string | undefined;
}

export interface GetManyAttributesResponse {
  attributes: GetAttributeResponse[];
  page: number;
  limit: number;
  totalItems: number;
  totalPages: number;
}

/** ====================================== Product ======================================// */
export interface Variant {
  value: string;
  options: string[];
}

export interface AttributeProduct {
  name: string;
  value: string;
}

export interface SKU {
  id: string;
  value: string;
  price: number;
  stock: number;
  image?: string | undefined;
}

/** ==================== GetProductRequest ====================// */
export interface GetProductRequest {
  processId?: string | undefined;
  id: string;
  shopId?: string | undefined;
}

export interface GetProductResponse {
  id: string;
  name: string;
  description?: string | undefined;
  provinceId: number;
  districtId: number;
  wardId: number;
  brandId?: string | undefined;
  brandName?: string | undefined;
  brandLogo?: string | undefined;
  categoryIds: string[];
  categories: CategoryProduct[];
  basePrice: number;
  virtualPrice: number;
  minPrice: number;
  maxPrice: number;
  totalStock: number;
  isAvailable: boolean;
  images: string[];
  sizeGuide?: string | undefined;
  variants: Variant[];
  attributes: AttributeProduct[];
  skus: SKU[];
  reviewIds: string[];
  ratingCount: number;
  averageRate: number;
  soldCount: number;
  viewCount: number;
  likeCount: number;
  shopId: string;
  status: string;
  isApproved: boolean;
  isHidden: boolean;
  createdAt: string;
  updatedAt: string;
}

/** ==================== GetManyProductsRequest ====================// */
export interface GetManyProductsRequest {
  processId?: string | undefined;
  page: number;
  limit: number;
  name?: string | undefined;
  status?: string | undefined;
  shopId?: string | undefined;
  brandIds: string[];
  categories: string[];
  minPrice?: number | undefined;
  maxPrice?: number | undefined;
  sortBy?: string | undefined;
  orderBy?: string | undefined;
  isApproved?: boolean | undefined;
}

export interface GetManyProductsResponse {
  products: GetProductResponse[];
  page: number;
  limit: number;
  totalItems: number;
  totalPages: number;
}

/**
 * ====================================== Notifications ======================================//
 * ==================== GetNotificationRequest ====================//
 */
export interface GetNotificationRequest {
  processId?: string | undefined;
  id: string;
  userId: string;
}

/** ==================== GetManyNotificationsRequest ====================// */
export interface GetManyNotificationsRequest {
  processId?: string | undefined;
  page: number;
  limit: number;
  userId: string;
}

export interface GetManyNotificationsResponse {
  notifications: NotificationResponse[];
  page: number;
  limit: number;
  totalItems: number;
  totalPages: number;
}

export interface Metadata {
  orderId?: string | undefined;
  articleId?: string | undefined;
}

export interface NotificationResponse {
  id: string;
  userId: string;
  type: string;
  title: string;
  description: string;
  link?: string | undefined;
  image?: string | undefined;
  isRead: boolean;
  metadata?: Metadata | undefined;
  createdAt: string;
  updatedAt: string;
}

/**
 * ====================================== Orders ======================================//
 * ==================== GetManyOrdersRequest ====================//
 */
export interface GetManyOrdersRequest {
  processId?: string | undefined;
  page: number;
  limit: number;
  paymentId?: string | undefined;
  status?: string | undefined;
  userId?: string | undefined;
  shopId?: string | undefined;
}

export interface OrderSummary {
  id: string;
  code: string;
  shopId: string;
  shopName: string;
  status: string;
  itemTotal: number;
  grandTotal: number;
  firstProductImage: string;
  firstProductName: string;
  createdAt: string;
}

export interface GetManyOrdersResponse {
  orders: OrderSummary[];
  page: number;
  limit: number;
  totalItems: number;
  totalPages: number;
}

/** ==================== GetOrderRequest ====================// */
export interface GetOrderRequest {
  processId?: string | undefined;
  orderId: string;
  userId?: string | undefined;
  shopId?: string | undefined;
}

export interface Receiver {
  name: string;
  phoneNumber: string;
  address: string;
}

export interface Timeline {
  status: string;
  at: string;
}

export interface OrderItemSnapshot {
  id: string;
  productId: string;
  productImage: string;
  productName: string;
  skuValue: string;
  quantity: number;
  price: number;
}

export interface GetOrderResponse {
  id: string;
  code: string;
  userId: string;
  shopId: string;
  shopName: string;
  status: string;
  paymentMethod: string;
  paymentStatus: string;
  paymentId: string;
  itemTotal: number;
  shippingFee: number;
  discount: number;
  grandTotal: number;
  receiver: Receiver | undefined;
  receiverName: string;
  receiverPhone: string;
  receiverAddress: string;
  timeline: Timeline | undefined;
  itemsSnapshot: OrderItemSnapshot[];
  firstProductName: string;
  firstProductImage: string;
  createdAt: string;
  updatedAt: string;
}

/**
 * ====================================== Video ======================================//
 * ==================== GetVideoRequest ====================//
 */
export interface GetVideoRequest {
  processId?: string | undefined;
  id: string;
  status?: string | undefined;
}

export interface VideoResponse {
  id: string;
  storageBucket: string;
  storageKey: string;
  filetype: string;
  size: number;
  status: string;
  duration: number;
  width: number;
  height: number;
  createdAt: string;
  updatedAt: string;
  title: string;
  likeCount: number;
  commentCount: number;
  authorId: string;
  authorUsername?: string | undefined;
  authorAvatar?: string | undefined;
  productId?: string | undefined;
}

/** ==================== GetRandomVideosRequest ====================// */
export interface GetRandomVideosRequest {
  processId?: string | undefined;
  limit: number;
}

export interface GetRandomVideosResponse {
  videos: VideoResponse[];
}

/** ==================== GetManyVideosRequest ====================// */
export interface GetManyVideosRequest {
  processId?: string | undefined;
  page: number;
  limit: number;
  userId?: string | undefined;
  status?: string | undefined;
  title?: string | undefined;
}

export interface VideoBasicInfo {
  id: string;
  size: number;
  duration: number;
  width: number;
  height: number;
  status: string;
  title: string;
  likeCount: number;
  commentCount: number;
  authorId: string;
  productId?: string | undefined;
}

export interface GetManyVideosResponse {
  page: number;
  limit: number;
  totalItems: number;
  totalPages: number;
  videos: VideoBasicInfo[];
}

/**
 * ====================================== Reviews ======================================//
 * ==================== GetManyProductReviewsRequest ====================//
 */
export interface GetManyProductReviewsRequest {
  processId?: string | undefined;
  page: number;
  limit: number;
  productId?: string | undefined;
  rating: number;
  userId?: string | undefined;
  shopId?: string | undefined;
}

/** ==================== GetReviewRequest ====================// */
export interface GetReviewRequest {
  processId?: string | undefined;
  id?: string | undefined;
  orderId?: string | undefined;
  orderItemId?: string | undefined;
}

export interface ReviewReply {
  id: string;
  reviewId: string;
  shopId: string;
  content: string;
  createdAt: string;
}

export interface ReviewItem {
  id: string;
  userId: string;
  rating: number;
  content: string;
  medias: string[];
  reply?: ReviewReply | undefined;
  createdAt: string;
  updatedAt?: string | undefined;
  productId: string;
  username?: string | undefined;
  avatar?: string | undefined;
  productName: string;
}

export interface ProductRatingStats {
  productId: string;
  averageRating: number;
  totalReviews: number;
  oneStarCount: number;
  twoStarCount: number;
  threeStarCount: number;
  fourStarCount: number;
  fiveStarCount: number;
}

export interface GetManyProductReviewsResponse {
  reviews: ReviewItem[];
  rating?: ProductRatingStats | undefined;
  page: number;
  limit: number;
  totalItems: number;
  totalPages: number;
}

/**
 * ====================================== Report ======================================//
 * ==================== GetReportRequest ====================//
 */
export interface GetReportRequest {
  processId?: string | undefined;
  id: string;
}

export interface ReportResponse {
  id: string;
  reporterId: string;
  targetId: string;
  targetType: string;
  category: string;
  title: string;
  description: string;
  status: string;
  note?: string | undefined;
  createdAt: string;
  updatedAt?: string | undefined;
}

/** ==================== GetManyReportsRequest ====================// */
export interface GetManyReportsRequest {
  processId?: string | undefined;
  page: number;
  limit: number;
  reporterId?: string | undefined;
  targetId?: string | undefined;
  targetType?: string | undefined;
  category?: string | undefined;
  status?: string | undefined;
}

export interface ReportListItem {
  id: string;
  reporterId: string;
  targetType: string;
  category: string;
  title: string;
  status: string;
}

export interface GetManyReportsResponse {
  reports: ReportListItem[];
  page: number;
  limit: number;
  totalItems: number;
  totalPages: number;
}

/** ====================================== Dashboard =====================================// */
export interface DashboardOrdersResponse {
  orderComplete: number;
  orderPending: number;
  orderCancelled: number;
  orderConfirmed: number;
  orderShipping: number;
  totalRevenue: number;
  totalOrders: number;
}

export interface Empty {
}

export const QUERY_SERVICE_PACKAGE_NAME = "QUERY_SERVICE";

export interface QueryServiceClient {
  getCategory(request: GetCategoryRequest): Observable<GetCategoryResponse>;

  getManyCategories(request: GetManyCategoriesRequest): Observable<GetManyCategoriesResponse>;

  getBrand(request: GetBrandRequest): Observable<GetBrandResponse>;

  getManyBrands(request: GetManyBrandsRequest): Observable<GetManyBrandsResponse>;

  getAttribute(request: GetAttributeRequest): Observable<GetAttributeResponse>;

  getManyAttributes(request: GetManyAttributesRequest): Observable<GetManyAttributesResponse>;

  getProduct(request: GetProductRequest): Observable<GetProductResponse>;

  getManyProducts(request: GetManyProductsRequest): Observable<GetManyProductsResponse>;

  getNotification(request: GetNotificationRequest): Observable<NotificationResponse>;

  getManyNotifications(request: GetManyNotificationsRequest): Observable<GetManyNotificationsResponse>;

  getManyOrders(request: GetManyOrdersRequest): Observable<GetManyOrdersResponse>;

  getOrder(request: GetOrderRequest): Observable<GetOrderResponse>;

  dashboardOrders(request: Empty): Observable<DashboardOrdersResponse>;

  getManyVideos(request: GetManyVideosRequest): Observable<GetManyVideosResponse>;

  getVideo(request: GetVideoRequest): Observable<VideoResponse>;

  getFeed(request: GetRandomVideosRequest): Observable<GetRandomVideosResponse>;

  getManyProductReviews(request: GetManyProductReviewsRequest): Observable<GetManyProductReviewsResponse>;

  getReview(request: GetReviewRequest): Observable<ReviewItem>;

  getReport(request: GetReportRequest): Observable<ReportResponse>;

  getManyReports(request: GetManyReportsRequest): Observable<GetManyReportsResponse>;
}

export interface QueryServiceController {
  getCategory(
    request: GetCategoryRequest,
  ): Promise<GetCategoryResponse> | Observable<GetCategoryResponse> | GetCategoryResponse;

  getManyCategories(
    request: GetManyCategoriesRequest,
  ): Promise<GetManyCategoriesResponse> | Observable<GetManyCategoriesResponse> | GetManyCategoriesResponse;

  getBrand(request: GetBrandRequest): Promise<GetBrandResponse> | Observable<GetBrandResponse> | GetBrandResponse;

  getManyBrands(
    request: GetManyBrandsRequest,
  ): Promise<GetManyBrandsResponse> | Observable<GetManyBrandsResponse> | GetManyBrandsResponse;

  getAttribute(
    request: GetAttributeRequest,
  ): Promise<GetAttributeResponse> | Observable<GetAttributeResponse> | GetAttributeResponse;

  getManyAttributes(
    request: GetManyAttributesRequest,
  ): Promise<GetManyAttributesResponse> | Observable<GetManyAttributesResponse> | GetManyAttributesResponse;

  getProduct(
    request: GetProductRequest,
  ): Promise<GetProductResponse> | Observable<GetProductResponse> | GetProductResponse;

  getManyProducts(
    request: GetManyProductsRequest,
  ): Promise<GetManyProductsResponse> | Observable<GetManyProductsResponse> | GetManyProductsResponse;

  getNotification(
    request: GetNotificationRequest,
  ): Promise<NotificationResponse> | Observable<NotificationResponse> | NotificationResponse;

  getManyNotifications(
    request: GetManyNotificationsRequest,
  ): Promise<GetManyNotificationsResponse> | Observable<GetManyNotificationsResponse> | GetManyNotificationsResponse;

  getManyOrders(
    request: GetManyOrdersRequest,
  ): Promise<GetManyOrdersResponse> | Observable<GetManyOrdersResponse> | GetManyOrdersResponse;

  getOrder(request: GetOrderRequest): Promise<GetOrderResponse> | Observable<GetOrderResponse> | GetOrderResponse;

  dashboardOrders(
    request: Empty,
  ): Promise<DashboardOrdersResponse> | Observable<DashboardOrdersResponse> | DashboardOrdersResponse;

  getManyVideos(
    request: GetManyVideosRequest,
  ): Promise<GetManyVideosResponse> | Observable<GetManyVideosResponse> | GetManyVideosResponse;

  getVideo(request: GetVideoRequest): Promise<VideoResponse> | Observable<VideoResponse> | VideoResponse;

  getFeed(
    request: GetRandomVideosRequest,
  ): Promise<GetRandomVideosResponse> | Observable<GetRandomVideosResponse> | GetRandomVideosResponse;

  getManyProductReviews(
    request: GetManyProductReviewsRequest,
  ): Promise<GetManyProductReviewsResponse> | Observable<GetManyProductReviewsResponse> | GetManyProductReviewsResponse;

  getReview(request: GetReviewRequest): Promise<ReviewItem> | Observable<ReviewItem> | ReviewItem;

  getReport(request: GetReportRequest): Promise<ReportResponse> | Observable<ReportResponse> | ReportResponse;

  getManyReports(
    request: GetManyReportsRequest,
  ): Promise<GetManyReportsResponse> | Observable<GetManyReportsResponse> | GetManyReportsResponse;
}

export function QueryServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      "getCategory",
      "getManyCategories",
      "getBrand",
      "getManyBrands",
      "getAttribute",
      "getManyAttributes",
      "getProduct",
      "getManyProducts",
      "getNotification",
      "getManyNotifications",
      "getManyOrders",
      "getOrder",
      "dashboardOrders",
      "getManyVideos",
      "getVideo",
      "getFeed",
      "getManyProductReviews",
      "getReview",
      "getReport",
      "getManyReports",
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("QueryService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("QueryService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const QUERY_SERVICE_NAME = "QueryService";
