// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.8.3
//   protoc               v6.33.5
// source: report.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "REPORT_SERVICE";

export enum ReportTargetType {
  REPORT_TARGET_UNKNOWN = 0,
  REPORT_TARGET_USER = 1,
  REPORT_TARGET_SELLER = 2,
  REPORT_TARGET_PRODUCT = 3,
  REPORT_TARGET_ORDER = 4,
  REPORT_TARGET_MESSAGE = 5,
  REPORT_TARGET_REVIEW = 6,
  UNRECOGNIZED = -1,
}

export enum ReportCategory {
  REPORT_CATEGORY_UNKNOWN = 0,
  REPORT_CATEGORY_SCAM = 1,
  REPORT_CATEGORY_FRAUD = 2,
  REPORT_CATEGORY_FAKE = 3,
  REPORT_CATEGORY_HARASSMENT = 4,
  REPORT_CATEGORY_SPAM = 5,
  UNRECOGNIZED = -1,
}

export enum ReportStatus {
  REPORT_STATUS_UNKNOWN = 0,
  REPORT_STATUS_PENDING = 1,
  REPORT_STATUS_REVIEWING = 2,
  REPORT_STATUS_RESOLVED = 3,
  REPORT_STATUS_REJECTED = 4,
  UNRECOGNIZED = -1,
}

export enum ReportActionType {
  REPORT_ACTION_UNKNOWN = 0,
  REPORT_ACTION_WARNING = 1,
  REPORT_ACTION_BAN_USER = 2,
  REPORT_ACTION_DELETE_PRODUCT = 3,
  REPORT_ACTION_REJECT = 4,
  UNRECOGNIZED = -1,
}

/** Report Entities */
export interface Report {
  id: string;
  reporterId: string;
  targetId: string;
  targetType: ReportTargetType;
  category: ReportCategory;
  title: string;
  description: string;
  status: ReportStatus;
  assignedAdminId: string;
  createdAt: string;
  updatedAt: string;
}

export interface ReportEvidence {
  id: string;
  reportId: string;
  url: string;
  /** image, video, file */
  evidenceType: string;
  note: string;
  createdAt: string;
}

/** COMMENTS */
export interface ReportComment {
  id: string;
  reportId: string;
  userId: string;
  /** user | admin */
  role: string;
  comment: string;
  createdAt: string;
}

/** HISTORY LOG */
export interface ReportHistory {
  id: string;
  reportId: string;
  oldStatus: ReportStatus;
  newStatus: ReportStatus;
  adminId: string;
  note: string;
  createdAt: string;
}

/** ACTIONS (ADMIN) */
export interface ReportAction {
  id: string;
  reportId: string;
  adminId: string;
  actionType: ReportActionType;
  reason: string;
  createdAt: string;
}

/** CREATE REPORT */
export interface CreateReportRequest {
  reporterId: string;
  targetId: string;
  targetType: ReportTargetType;
  category: ReportCategory;
  title: string;
  description: string;
}

export interface CreateReportResponse {
  report: Report | undefined;
}

/** GET REPORT FULL DETAILS */
export interface GetReportRequest {
  id: string;
}

export interface GetReportResponse {
  report: Report | undefined;
  evidences: ReportEvidence[];
  comments: ReportComment[];
  history: ReportHistory[];
  actions: ReportAction[];
}

/** LIST REPORTS */
export interface ListReportsRequest {
  targetId: string;
  targetType: ReportTargetType;
  status: ReportStatus;
  page: number;
  limit: number;
  /** created_at, status */
  sortBy: string;
  /** asc | desc */
  sortOrder: string;
}

export interface ListReportsResponse {
  reports: Report[];
  total: number;
  page: number;
  limit: number;
}

/** ADD EVIDENCE */
export interface AddEvidenceRequest {
  reportId: string;
  url: string;
  evidenceType: string;
  note: string;
}

export interface AddEvidenceResponse {
  evidence: ReportEvidence | undefined;
}

/** ADD COMMENT */
export interface AddCommentRequest {
  reportId: string;
  userId: string;
  role: string;
  comment: string;
}

export interface AddCommentResponse {
  comment: ReportComment | undefined;
}

/** UPDATE STATUS */
export interface UpdateReportStatusRequest {
  reportId: string;
  adminId: string;
  newStatus: ReportStatus;
  note: string;
}

export interface UpdateReportStatusResponse {
  history: ReportHistory | undefined;
}

/** CREATE ACTION */
export interface CreateReportActionRequest {
  reportId: string;
  adminId: string;
  actionType: ReportActionType;
  reason: string;
}

export interface CreateReportActionResponse {
  action: ReportAction | undefined;
}

/** SOFT DELETE REPORT */
export interface SoftDeleteReportRequest {
  reportId: string;
  requesterId: string;
}

export interface SoftDeleteReportResponse {
  success: boolean;
  message: string;
}

/** HARD DELETE REPORT (Admin only) */
export interface HardDeleteReportRequest {
  reportId: string;
  adminId: string;
}

export interface HardDeleteReportResponse {
  success: boolean;
  message: string;
}

/** GET DASHBOARD (Admin only) */
export interface GetDashboardRequest {
}

export interface GetDashboardResponse {
  totalReports: number;
  pendingReports: number;
  inProgressReports: number;
  resolvedReports: number;
  rejectedReports: number;
}

export const REPORT_SERVICE_PACKAGE_NAME = "REPORT_SERVICE";

export interface ReportServiceClient {
  createReport(request: CreateReportRequest): Observable<CreateReportResponse>;

  getReport(request: GetReportRequest): Observable<GetReportResponse>;

  listReports(request: ListReportsRequest): Observable<ListReportsResponse>;

  addEvidence(request: AddEvidenceRequest): Observable<AddEvidenceResponse>;

  addComment(request: AddCommentRequest): Observable<AddCommentResponse>;

  updateReportStatus(request: UpdateReportStatusRequest): Observable<UpdateReportStatusResponse>;

  createReportAction(request: CreateReportActionRequest): Observable<CreateReportActionResponse>;

  softDeleteReport(request: SoftDeleteReportRequest): Observable<SoftDeleteReportResponse>;

  hardDeleteReport(request: HardDeleteReportRequest): Observable<HardDeleteReportResponse>;

  getDashboard(request: GetDashboardRequest): Observable<GetDashboardResponse>;
}

export interface ReportServiceController {
  createReport(
    request: CreateReportRequest,
  ): Promise<CreateReportResponse> | Observable<CreateReportResponse> | CreateReportResponse;

  getReport(request: GetReportRequest): Promise<GetReportResponse> | Observable<GetReportResponse> | GetReportResponse;

  listReports(
    request: ListReportsRequest,
  ): Promise<ListReportsResponse> | Observable<ListReportsResponse> | ListReportsResponse;

  addEvidence(
    request: AddEvidenceRequest,
  ): Promise<AddEvidenceResponse> | Observable<AddEvidenceResponse> | AddEvidenceResponse;

  addComment(
    request: AddCommentRequest,
  ): Promise<AddCommentResponse> | Observable<AddCommentResponse> | AddCommentResponse;

  updateReportStatus(
    request: UpdateReportStatusRequest,
  ): Promise<UpdateReportStatusResponse> | Observable<UpdateReportStatusResponse> | UpdateReportStatusResponse;

  createReportAction(
    request: CreateReportActionRequest,
  ): Promise<CreateReportActionResponse> | Observable<CreateReportActionResponse> | CreateReportActionResponse;

  softDeleteReport(
    request: SoftDeleteReportRequest,
  ): Promise<SoftDeleteReportResponse> | Observable<SoftDeleteReportResponse> | SoftDeleteReportResponse;

  hardDeleteReport(
    request: HardDeleteReportRequest,
  ): Promise<HardDeleteReportResponse> | Observable<HardDeleteReportResponse> | HardDeleteReportResponse;

  getDashboard(
    request: GetDashboardRequest,
  ): Promise<GetDashboardResponse> | Observable<GetDashboardResponse> | GetDashboardResponse;
}

export function ReportServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      "createReport",
      "getReport",
      "listReports",
      "addEvidence",
      "addComment",
      "updateReportStatus",
      "createReportAction",
      "softDeleteReport",
      "hardDeleteReport",
      "getDashboard",
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("ReportService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("ReportService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const REPORT_SERVICE_NAME = "ReportService";
