// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.8.3
//   protoc               v6.33.5
// source: review.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "REVIEW_SERVICE";

export enum ReviewRating {
  REVIEW_RATING_UNSPECIFIED = 0,
  RATING_1 = 1,
  RATING_2 = 2,
  RATING_3 = 3,
  RATING_4 = 4,
  RATING_5 = 5,
  UNRECOGNIZED = -1,
}

/** Entities / DTOs */
export interface ReviewReply {
  id: string;
  reviewId: string;
  sellerId: string;
  content: string;
  createdAt: string;
  updatedAt: string;
}

export interface Review {
  id: string;
  userId: string;
  productId: string;
  orderItemId: string;
  orderId: string;
  rating: ReviewRating;
  content: string;
  medias: string[];
  replies: ReviewReply | undefined;
  createdAt: string;
  updatedAt: string;
}

export interface ProductRatingStats {
  productId: string;
  averageRating: number;
  totalReviews: number;
  oneStarCount: number;
  twoStarCount: number;
  threeStarCount: number;
  fourStarCount: number;
  fiveStarCount: number;
  reviewsWithMediaCount: number;
}

export interface SellerRatingStats {
  sellerId: string;
  averageRating: number;
  totalReviews: number;
  oneStarCount: number;
  twoStarCount: number;
  threeStarCount: number;
  fourStarCount: number;
  fiveStarCount: number;
}

export interface DashboardReviewStats {
  totalReviews: number;
  oneStarCount: number;
  twoStarCount: number;
  threeStarCount: number;
  fourStarCount: number;
  fiveStarCount: number;
  reviewsWithMedia: number;
}

export interface DashboardSellerReviewStats {
  totalReviews: number;
  averageRating: number;
  oneStarCount: number;
  twoStarCount: number;
  threeStarCount: number;
  fourStarCount: number;
  fiveStarCount: number;
  reviewsWithMedia: number;
}

/** Paging helper */
export interface PageInfo {
  page: number;
  limit: number;
  total: number;
}

export interface CreateReviewRequest {
  userId: string;
  orderItemId: string;
  orderId: string;
  rating: ReviewRating;
  content: string;
  medias: string[];
}

export interface CreateReviewResponse {
  review: Review | undefined;
}

export interface CreateReplyRequest {
  sellerId: string;
  reviewId: string;
  content: string;
}

export interface CreateReplyResponse {
  review: Review | undefined;
}

export interface UpdateReviewRequest {
  userId: string;
  id: string;
  rating?: ReviewRating | undefined;
  content?: string | undefined;
  medias: string[];
}

export interface UpdateReviewResponse {
  review: Review | undefined;
}

export interface UpdateReplyRequest {
  sellerId: string;
  id: string;
  content: string;
}

export interface UpdateReplyResponse {
  review: Review | undefined;
}

export interface DeleteReviewRequest {
  userId: string;
  id: string;
}

export interface DeleteReviewResponse {
  success: boolean;
}

export interface DeleteReplyRequest {
  sellerId: string;
  id: string;
}

export interface DeleteReplyResponse {
  success: boolean;
}

export interface GetReviewRequest {
  userId: string;
  id: string;
}

export interface GetReviewResponse {
  review: Review | undefined;
}

export interface GetMyReviewsRequest {
  userId: string;
  productId: string;
  fromDate: string;
  toDate: string;
  minRating: number;
  maxRating: number;
  sortBy: string;
  page: number;
  limit: number;
}

export interface GetMyReviewsResponse {
  items: Review[];
  pageInfo: PageInfo | undefined;
}

export interface GetReviewsAdminRequest {
  adminId: string;
  userId: string;
  sellerId: string;
  productId: string;
  fromDate: string;
  toDate: string;
  minRating: number;
  maxRating: number;
  sortBy: string;
  page: number;
  limit: number;
}

export interface GetReviewsAdminResponse {
  items: Review[];
  pageInfo: PageInfo | undefined;
}

/** Map với GetReviewByIdAdmin(string reviewId) */
export interface GetReviewByIdAdminRequest {
  adminId: string;
  id: string;
}

export interface GetReviewByIdAdminResponse {
  review: Review | undefined;
}

export interface GetProductRatingRequest {
  productId: string;
}

export interface GetProductRatingResponse {
  rating: ProductRatingStats | undefined;
}

export interface GetSellerRatingRequest {
  sellerId: string;
}

export interface GetSellerRatingResponse {
  stats: SellerRatingStats | undefined;
}

export interface GetDashboardReviewStatsRequest {
  adminId: string;
}

export interface GetDashboardReviewStatsResponse {
  stats: DashboardReviewStats | undefined;
}

export interface GetDashboardSellerReviewStatsRequest {
  sellerId: string;
  sellerIdAuth: string;
}

export interface GetDashboardSellerReviewStatsResponse {
  stats: DashboardSellerReviewStats | undefined;
}

export const REVIEW_SERVICE_PACKAGE_NAME = "REVIEW_SERVICE";

export interface ReviewServiceClient {
  /** Admin get */

  getReviewsAdmin(request: GetReviewsAdminRequest): Observable<GetReviewsAdminResponse>;

  getReviewByIdAdmin(request: GetReviewByIdAdminRequest): Observable<GetReviewByIdAdminResponse>;

  /** User / Seller get */

  getMyReviews(request: GetMyReviewsRequest): Observable<GetMyReviewsResponse>;

  getProductRating(request: GetProductRatingRequest): Observable<GetProductRatingResponse>;

  getSellerRating(request: GetSellerRatingRequest): Observable<GetSellerRatingResponse>;

  /** Single review for client */

  getReview(request: GetReviewRequest): Observable<GetReviewResponse>;

  /** Create */

  createReview(request: CreateReviewRequest): Observable<CreateReviewResponse>;

  createReply(request: CreateReplyRequest): Observable<CreateReplyResponse>;

  /** Update */

  updateReview(request: UpdateReviewRequest): Observable<UpdateReviewResponse>;

  updateReply(request: UpdateReplyRequest): Observable<UpdateReplyResponse>;

  /** Delete */

  deleteReview(request: DeleteReviewRequest): Observable<DeleteReviewResponse>;

  deleteReply(request: DeleteReplyRequest): Observable<DeleteReplyResponse>;

  /** Dashboard */

  getDashboardReviewStats(request: GetDashboardReviewStatsRequest): Observable<GetDashboardReviewStatsResponse>;

  getDashboardSellerReviewStats(
    request: GetDashboardSellerReviewStatsRequest,
  ): Observable<GetDashboardSellerReviewStatsResponse>;
}

export interface ReviewServiceController {
  /** Admin get */

  getReviewsAdmin(
    request: GetReviewsAdminRequest,
  ): Promise<GetReviewsAdminResponse> | Observable<GetReviewsAdminResponse> | GetReviewsAdminResponse;

  getReviewByIdAdmin(
    request: GetReviewByIdAdminRequest,
  ): Promise<GetReviewByIdAdminResponse> | Observable<GetReviewByIdAdminResponse> | GetReviewByIdAdminResponse;

  /** User / Seller get */

  getMyReviews(
    request: GetMyReviewsRequest,
  ): Promise<GetMyReviewsResponse> | Observable<GetMyReviewsResponse> | GetMyReviewsResponse;

  getProductRating(
    request: GetProductRatingRequest,
  ): Promise<GetProductRatingResponse> | Observable<GetProductRatingResponse> | GetProductRatingResponse;

  getSellerRating(
    request: GetSellerRatingRequest,
  ): Promise<GetSellerRatingResponse> | Observable<GetSellerRatingResponse> | GetSellerRatingResponse;

  /** Single review for client */

  getReview(request: GetReviewRequest): Promise<GetReviewResponse> | Observable<GetReviewResponse> | GetReviewResponse;

  /** Create */

  createReview(
    request: CreateReviewRequest,
  ): Promise<CreateReviewResponse> | Observable<CreateReviewResponse> | CreateReviewResponse;

  createReply(
    request: CreateReplyRequest,
  ): Promise<CreateReplyResponse> | Observable<CreateReplyResponse> | CreateReplyResponse;

  /** Update */

  updateReview(
    request: UpdateReviewRequest,
  ): Promise<UpdateReviewResponse> | Observable<UpdateReviewResponse> | UpdateReviewResponse;

  updateReply(
    request: UpdateReplyRequest,
  ): Promise<UpdateReplyResponse> | Observable<UpdateReplyResponse> | UpdateReplyResponse;

  /** Delete */

  deleteReview(
    request: DeleteReviewRequest,
  ): Promise<DeleteReviewResponse> | Observable<DeleteReviewResponse> | DeleteReviewResponse;

  deleteReply(
    request: DeleteReplyRequest,
  ): Promise<DeleteReplyResponse> | Observable<DeleteReplyResponse> | DeleteReplyResponse;

  /** Dashboard */

  getDashboardReviewStats(
    request: GetDashboardReviewStatsRequest,
  ):
    | Promise<GetDashboardReviewStatsResponse>
    | Observable<GetDashboardReviewStatsResponse>
    | GetDashboardReviewStatsResponse;

  getDashboardSellerReviewStats(
    request: GetDashboardSellerReviewStatsRequest,
  ):
    | Promise<GetDashboardSellerReviewStatsResponse>
    | Observable<GetDashboardSellerReviewStatsResponse>
    | GetDashboardSellerReviewStatsResponse;
}

export function ReviewServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      "getReviewsAdmin",
      "getReviewByIdAdmin",
      "getMyReviews",
      "getProductRating",
      "getSellerRating",
      "getReview",
      "createReview",
      "createReply",
      "updateReview",
      "updateReply",
      "deleteReview",
      "deleteReply",
      "getDashboardReviewStats",
      "getDashboardSellerReviewStats",
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("ReviewService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("ReviewService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const REVIEW_SERVICE_NAME = "ReviewService";
