// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.8.3
//   protoc               v6.33.5
// source: role.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "ROLE_SERVICE";

/** ==================== GetRole ====================// */
export interface GetRoleRequest {
  processId?: string | undefined;
  id?: string | undefined;
  name?: string | undefined;
  withInheritance: boolean;
}

export interface Permissions {
  id: string;
  path: string;
  method: string;
}

export interface RoleResponse {
  id: string;
  name: string;
  description: string;
  userIds: string[];
  createdById: string;
  updatedById: string;
  deletedById: string;
  deletedAt: string;
  createdAt: string;
  updatedAt: string;
  permissions: Permissions[];
}

/** ==================== GetManyRoles ====================// */
export interface GetManyRolesRequest {
  processId?: string | undefined;
  page?: number | undefined;
  limit?: number | undefined;
}

export interface GetManyRolesResponse {
  roles: RoleResponse[];
  page: number;
  limit: number;
  totalItems: number;
  totalPages: number;
}

/** ==================== CreateRole ====================// */
export interface CreateRoleRequest {
  processId?: string | undefined;
  name: string;
  description: string;
  createdById?: string | undefined;
}

/** ==================== UpdateRole ====================// */
export interface UpdateRoleRequest {
  processId?: string | undefined;
  id: string;
  name?: string | undefined;
  description?: string | undefined;
  updatedById?: string | undefined;
  permissionIds: string[];
}

/** ==================== DeleteRole ====================// */
export interface DeleteRoleRequest {
  processId?: string | undefined;
  id: string;
  deletedById: string;
}

/** ==================== GetManyUniquePermissions ====================// */
export interface GetManyUniquePermissionsRequest {
  names: string[];
}

export interface GetManyUniquePermissionsResponse {
  permissions: Permissions[];
}

/** ==================== CreatePermission ====================// */
export interface CreatePermissionRequest {
  processId?: string | undefined;
  name: string;
  description?: string | undefined;
  module: string;
  path: string;
  method: string;
  createdById?: string | undefined;
}

/** ==================== CreateManyPermissions ====================// */
export interface CreateManyPermissionsRequest {
  permissions: CreatePermissionRequest[];
}

/** ==================== DeleteManyPermissions ====================// */
export interface DeleteManyPermissionsRequest {
  ids: string[];
}

export interface CountResponse {
  count: number;
}

export const ROLE_SERVICE_PACKAGE_NAME = "ROLE_SERVICE";

export interface RoleServiceClient {
  getRole(request: GetRoleRequest): Observable<RoleResponse>;

  getManyRoles(request: GetManyRolesRequest): Observable<GetManyRolesResponse>;

  createRole(request: CreateRoleRequest): Observable<RoleResponse>;

  updateRole(request: UpdateRoleRequest): Observable<RoleResponse>;

  deleteRole(request: DeleteRoleRequest): Observable<RoleResponse>;

  getManyUniquePermissions(request: GetManyUniquePermissionsRequest): Observable<GetManyUniquePermissionsResponse>;

  createPermission(request: CreatePermissionRequest): Observable<Permissions>;

  createManyPermissions(request: CreateManyPermissionsRequest): Observable<CountResponse>;

  deleteManyPermissions(request: DeleteManyPermissionsRequest): Observable<CountResponse>;
}

export interface RoleServiceController {
  getRole(request: GetRoleRequest): Promise<RoleResponse> | Observable<RoleResponse> | RoleResponse;

  getManyRoles(
    request: GetManyRolesRequest,
  ): Promise<GetManyRolesResponse> | Observable<GetManyRolesResponse> | GetManyRolesResponse;

  createRole(request: CreateRoleRequest): Promise<RoleResponse> | Observable<RoleResponse> | RoleResponse;

  updateRole(request: UpdateRoleRequest): Promise<RoleResponse> | Observable<RoleResponse> | RoleResponse;

  deleteRole(request: DeleteRoleRequest): Promise<RoleResponse> | Observable<RoleResponse> | RoleResponse;

  getManyUniquePermissions(
    request: GetManyUniquePermissionsRequest,
  ):
    | Promise<GetManyUniquePermissionsResponse>
    | Observable<GetManyUniquePermissionsResponse>
    | GetManyUniquePermissionsResponse;

  createPermission(request: CreatePermissionRequest): Promise<Permissions> | Observable<Permissions> | Permissions;

  createManyPermissions(
    request: CreateManyPermissionsRequest,
  ): Promise<CountResponse> | Observable<CountResponse> | CountResponse;

  deleteManyPermissions(
    request: DeleteManyPermissionsRequest,
  ): Promise<CountResponse> | Observable<CountResponse> | CountResponse;
}

export function RoleServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      "getRole",
      "getManyRoles",
      "createRole",
      "updateRole",
      "deleteRole",
      "getManyUniquePermissions",
      "createPermission",
      "createManyPermissions",
      "deleteManyPermissions",
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("RoleService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("RoleService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const ROLE_SERVICE_NAME = "RoleService";
