// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               v7.34.1
// source: shop.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "SHOP_SERVICE";

export interface GetManyMerchantsRequest {
  processId?: string | undefined;
  page: number;
  limit: number;
  userId?: string | undefined;
  legalName?: string | undefined;
  type?: string | undefined;
  approvalStatus?: string | undefined;
  canSell?: boolean | undefined;
}

export interface GetMerchantRequest {
  processId?: string | undefined;
  id: string;
}

export interface CreateMerchantRequest {
  processId?: string | undefined;
  userId: string;
  type: string;
  legalName: string;
  taxCode?: string | undefined;
  createdById?: string | undefined;
}

export interface UpdateMerchantRequest {
  processId?: string | undefined;
  id: string;
  userId?: string | undefined;
  type?: string | undefined;
  legalName?: string | undefined;
  taxCode?: string | undefined;
  approvalStatus?: string | undefined;
  canSell?: boolean | undefined;
  updatedById?: string | undefined;
}

export interface DeleteMerchantRequest {
  processId?: string | undefined;
  id: string;
  deletedById?: string | undefined;
}

export interface MerchantResponse {
  id: string;
  userId: string;
  type: string;
  legalName: string;
  taxCode: string;
  approvalStatus: string;
  canSell: boolean;
  createdById: string;
  updatedById: string;
  deletedById: string;
  deletedAt: string;
  createdAt: string;
  updatedAt: string;
}

export interface GetManyMerchantsResponse {
  merchants: MerchantResponse[];
  page: number;
  limit: number;
  totalItems: number;
  totalPages: number;
}

export interface GetManyShopsRequest {
  processId?: string | undefined;
  page: number;
  limit: number;
  merchantId?: string | undefined;
  name?: string | undefined;
  status?: string | undefined;
}

export interface GetShopRequest {
  processId?: string | undefined;
  id: string;
}

export interface CreateShopRequest {
  processId?: string | undefined;
  merchantId: string;
  name: string;
  description: string;
  logo?: string | undefined;
  banner?: string | undefined;
  phone?: string | undefined;
  status: string;
  pickupAddress?: string | undefined;
  returnAddress?: string | undefined;
  createdById?: string | undefined;
}

export interface UpdateShopRequest {
  processId?: string | undefined;
  id: string;
  merchantId?: string | undefined;
  name?: string | undefined;
  description?: string | undefined;
  logo?: string | undefined;
  banner?: string | undefined;
  phone?: string | undefined;
  status?: string | undefined;
  pickupAddress?: string | undefined;
  returnAddress?: string | undefined;
  updatedById?: string | undefined;
}

export interface DeleteShopRequest {
  processId?: string | undefined;
  id: string;
  deletedById?: string | undefined;
}

export interface ShopResponse {
  id: string;
  merchantId: string;
  name: string;
  description: string;
  logo: string;
  banner: string;
  phone: string;
  status: string;
  pickupAddress: string;
  returnAddress: string;
  createdById: string;
  updatedById: string;
  deletedById: string;
  deletedAt: string;
  createdAt: string;
  updatedAt: string;
}

export interface GetManyShopsResponse {
  shops: ShopResponse[];
  page: number;
  limit: number;
  totalItems: number;
  totalPages: number;
}

export const SHOP_SERVICE_PACKAGE_NAME = "SHOP_SERVICE";

export interface MerchantModuleClient {
  getManyMerchants(request: GetManyMerchantsRequest): Observable<GetManyMerchantsResponse>;

  getMerchant(request: GetMerchantRequest): Observable<MerchantResponse>;

  createMerchant(request: CreateMerchantRequest): Observable<MerchantResponse>;

  updateMerchant(request: UpdateMerchantRequest): Observable<MerchantResponse>;

  deleteMerchant(request: DeleteMerchantRequest): Observable<MerchantResponse>;
}

export interface MerchantModuleController {
  getManyMerchants(
    request: GetManyMerchantsRequest,
  ): Promise<GetManyMerchantsResponse> | Observable<GetManyMerchantsResponse> | GetManyMerchantsResponse;

  getMerchant(request: GetMerchantRequest): Promise<MerchantResponse> | Observable<MerchantResponse> | MerchantResponse;

  createMerchant(
    request: CreateMerchantRequest,
  ): Promise<MerchantResponse> | Observable<MerchantResponse> | MerchantResponse;

  updateMerchant(
    request: UpdateMerchantRequest,
  ): Promise<MerchantResponse> | Observable<MerchantResponse> | MerchantResponse;

  deleteMerchant(
    request: DeleteMerchantRequest,
  ): Promise<MerchantResponse> | Observable<MerchantResponse> | MerchantResponse;
}

export function MerchantModuleControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      "getManyMerchants",
      "getMerchant",
      "createMerchant",
      "updateMerchant",
      "deleteMerchant",
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("MerchantModule", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("MerchantModule", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const MERCHANT_MODULE_SERVICE_NAME = "MerchantModule";

export interface ShopModuleClient {
  getManyShops(request: GetManyShopsRequest): Observable<GetManyShopsResponse>;

  getShop(request: GetShopRequest): Observable<ShopResponse>;

  createShop(request: CreateShopRequest): Observable<ShopResponse>;

  updateShop(request: UpdateShopRequest): Observable<ShopResponse>;

  deleteShop(request: DeleteShopRequest): Observable<ShopResponse>;
}

export interface ShopModuleController {
  getManyShops(
    request: GetManyShopsRequest,
  ): Promise<GetManyShopsResponse> | Observable<GetManyShopsResponse> | GetManyShopsResponse;

  getShop(request: GetShopRequest): Promise<ShopResponse> | Observable<ShopResponse> | ShopResponse;

  createShop(request: CreateShopRequest): Promise<ShopResponse> | Observable<ShopResponse> | ShopResponse;

  updateShop(request: UpdateShopRequest): Promise<ShopResponse> | Observable<ShopResponse> | ShopResponse;

  deleteShop(request: DeleteShopRequest): Promise<ShopResponse> | Observable<ShopResponse> | ShopResponse;
}

export function ShopModuleControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["getManyShops", "getShop", "createShop", "updateShop", "deleteShop"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("ShopModule", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("ShopModule", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const SHOP_MODULE_SERVICE_NAME = "ShopModule";
