// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.8.3
//   protoc               v6.33.5
// source: user-access.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "USER_ACCESS_SERVICE";

/** ==================== Login ====================// */
export interface LoginRequest {
  processId?: string | undefined;
  username: string;
  password: string;
}

export interface LoginResponse {
  accessToken: string;
  refreshToken: string;
  expiresIn: number;
  refreshExpiresIn: number;
}

/** ==================== Refresh Token ====================// */
export interface RefreshTokenRequest {
  processId?: string | undefined;
  refreshToken: string;
}

export interface LogoutRequest {
  processId?: string | undefined;
  refreshToken: string;
}

/** ==================== Register ====================// */
export interface RegisterRequest {
  processId?: string | undefined;
  firstName: string;
  lastName: string;
  username: string;
  email: string;
  password: string;
  phoneNumber: string;
  gender: string;
  code: string;
}

export interface MessageResponse {
  message: string;
}

/** ==================== Change Password ====================// */
export interface ChangePasswordRequest {
  processId?: string | undefined;
  email: string;
  password: string;
  code: string;
}

/** ==================== Verify Token ====================// */
export interface VerifyTokenRequest {
  processId?: string | undefined;
  token: string;
  withPermissions?: boolean | undefined;
}

export interface VerifyTokenResponse {
  isValid: boolean;
  userId: string;
  roleId: string;
  roleName: string;
  shopId?: string | undefined;
  permissions: Permissions[];
}

export interface Permissions {
  id: string;
  path: string;
  method: string;
}

/** ==================== GetUser ====================// */
export interface GetUserRequest {
  processId?: string | undefined;
  id?: string | undefined;
  email?: string | undefined;
  phoneNumber?: string | undefined;
}

/** ==================== UpdateUser ====================// */
export interface UpdateUserRequest {
  processId?: string | undefined;
  id: string;
  firstName?: string | undefined;
  lastName?: string | undefined;
  phoneNumber?: string | undefined;
  avatar?: string | undefined;
  gender?: string | undefined;
  birthday?: string | undefined;
}

/** ==================== CreateUser ====================// */
export interface CreateUserRequest {
  processId?: string | undefined;
  firstName: string;
  lastName: string;
  email: string;
  username: string;
  phoneNumber: string;
  avatar: string;
  gender: string;
  roleId: string;
  roleName: string;
}

export interface UserResponse {
  id: string;
  firstName: string;
  lastName: string;
  email: string;
  username: string;
  phoneNumber: string;
  avatar: string;
  /** ISO 8601 format */
  birthday: string;
  gender: string;
  status: string;
  roleId: string;
  roleName: string;
  createdById: string;
  updatedById: string;
  deletedById: string;
  deletedAt: string;
  createdAt: string;
  updatedAt: string;
}

/** ==================== CheckParticipantExists ====================// */
export interface CheckParticipantExistsRequest {
  processId?: string | undefined;
  participantIds: string[];
}

export interface CheckParticipantExistsResponse {
  count: number;
}

/** ==================== GetManyUser ====================// */
export interface GetManyUsersRequest {
  processId?: string | undefined;
  page: number;
  limit: number;
  email?: string | undefined;
  phoneNumber?: string | undefined;
  firstName?: string | undefined;
  lastName?: string | undefined;
  username?:
    | string
    | undefined;
  /** "MALE" | "FEMALE" | "OTHER" */
  gender?:
    | string
    | undefined;
  /** "ACTIVE" | "INACTIVE" | "BLOCKED" */
  status?: string | undefined;
  roleName?: string | undefined;
}

export interface GetManyUsersResponse {
  page: number;
  limit: number;
  totalItems: number;
  totalPages: number;
  users: UserBasicInfo[];
}

export interface UserBasicInfo {
  id: string;
  email: string;
  phoneNumber: string;
  firstName: string;
  lastName: string;
  gender: string;
  status: string;
  roleName: string;
}

/** ==================== GetManyInformationUsers ====================// */
export interface GetManyInformationUsersRequest {
  processId?: string | undefined;
  userIds: string[];
}

export interface GetManyInformationUsersResponse {
  users: { [key: string]: UserInformation };
}

export interface GetManyInformationUsersResponse_UsersEntry {
  key: string;
  value: UserInformation | undefined;
}

export interface UserInformation {
  username: string;
  avatar?: string | undefined;
}

/** ==================== GetShop ====================// */
export interface GetShopRequest {
  processId?: string | undefined;
  id?: string | undefined;
  userId?: string | undefined;
}

export interface ShopResponse {
  id: string;
  name: string;
  description: string;
  ownerId: string;
  logo?: string | undefined;
  address?: string | undefined;
  phone?: string | undefined;
  rating: number;
  isOpen: boolean;
  createdById: string;
  updatedById: string;
  deletedById: string;
  deletedAt: string;
  createdAt: string;
  updatedAt: string;
}

/** ==================== GetManyShops ====================// */
export interface GetManyShopsRequest {
  processId?: string | undefined;
  page: number;
  limit: number;
  userId?: string | undefined;
}

export interface GetManyShopsResponse {
  shops: ShopResponse[];
  page: number;
  limit: number;
  totalItems: number;
  totalPages: number;
}

/** ==================== CreateShop ====================// */
export interface CreateShopRequest {
  processId?: string | undefined;
  name: string;
  description: string;
  ownerId: string;
  logo?: string | undefined;
  address?: string | undefined;
  phone?: string | undefined;
}

/** ==================== UpdateShop ====================// */
export interface UpdateShopRequest {
  processId?: string | undefined;
  id: string;
  ownerId: string;
  name?: string | undefined;
  description?: string | undefined;
  logo?: string | undefined;
  address?: string | undefined;
  phone?: string | undefined;
  isOpen?: boolean | undefined;
}

/** ==================== ValidateShops ====================// */
export interface ValidateShopsRequest {
  processId?: string | undefined;
  shopIds: string[];
}

export interface ValidateShop {
  id: string;
  name: string;
}

export interface ValidateShopsResponse {
  shops: ValidateShop[];
}

/** ==================== GetManyAddresses ====================// */
export interface GetManyAddressesRequest {
  processId?: string | undefined;
  userId: string;
  page: number;
  limit: number;
}

export interface GetManyAddressesResponse {
  addresses: AddressResponse[];
  page: number;
  limit: number;
  totalItems: number;
  totalPages: number;
}

/** ==================== GetAddress ====================// */
export interface GetAddressRequest {
  processId?: string | undefined;
  id: string;
  userId: string;
}

/** ==================== CreateAddress ====================// */
export interface CreateAddressRequest {
  processId?: string | undefined;
  userId: string;
  name: string;
  address: string;
  ward?: string | undefined;
  district?: string | undefined;
  province?: string | undefined;
  isDefault: boolean;
}

/** ==================== UpdateAddress ====================// */
export interface UpdateAddressRequest {
  processId?: string | undefined;
  id: string;
  userId?: string | undefined;
  name?: string | undefined;
  address?: string | undefined;
  ward?: string | undefined;
  district?: string | undefined;
  province?: string | undefined;
  isDefault?: boolean | undefined;
}

/** ==================== DeleteAddress ====================// */
export interface DeleteAddressRequest {
  processId?: string | undefined;
  id: string;
  userId: string;
}

/** ==================== AddressResponse ====================// */
export interface AddressResponse {
  id: string;
  userId: string;
  name: string;
  address: string;
  ward: string;
  district: string;
  province: string;
  isDefault: boolean;
  createdAt: string;
  updatedAt: string;
}

/** ==================== SendVerificationCodeRequest ====================// */
export interface SendVerificationCodeRequest {
  processId?: string | undefined;
  email: string;
  type: string;
}

export const USER_ACCESS_SERVICE_PACKAGE_NAME = "USER_ACCESS_SERVICE";

export interface UserAccessServiceClient {
  loginDirectAccessGrants(request: LoginRequest): Observable<LoginResponse>;

  refreshToken(request: RefreshTokenRequest): Observable<LoginResponse>;

  logout(request: LogoutRequest): Observable<MessageResponse>;

  register(request: RegisterRequest): Observable<MessageResponse>;

  verifyToken(request: VerifyTokenRequest): Observable<VerifyTokenResponse>;

  changePassword(request: ChangePasswordRequest): Observable<MessageResponse>;

  sendOtp(request: SendVerificationCodeRequest): Observable<MessageResponse>;

  getUser(request: GetUserRequest): Observable<UserResponse>;

  getManyUsers(request: GetManyUsersRequest): Observable<GetManyUsersResponse>;

  updateUser(request: UpdateUserRequest): Observable<UserResponse>;

  createUser(request: CreateUserRequest): Observable<UserResponse>;

  checkParticipantExists(request: CheckParticipantExistsRequest): Observable<CheckParticipantExistsResponse>;

  getManyInformationUsers(request: GetManyInformationUsersRequest): Observable<GetManyInformationUsersResponse>;

  getShop(request: GetShopRequest): Observable<ShopResponse>;

  getManyShops(request: GetManyShopsRequest): Observable<GetManyShopsResponse>;

  createShop(request: CreateShopRequest): Observable<ShopResponse>;

  updateShop(request: UpdateShopRequest): Observable<ShopResponse>;

  validateShops(request: ValidateShopsRequest): Observable<ValidateShopsResponse>;

  getManyAddresses(request: GetManyAddressesRequest): Observable<GetManyAddressesResponse>;

  getAddress(request: GetAddressRequest): Observable<AddressResponse>;

  createAddress(request: CreateAddressRequest): Observable<AddressResponse>;

  updateAddress(request: UpdateAddressRequest): Observable<AddressResponse>;

  deleteAddress(request: DeleteAddressRequest): Observable<AddressResponse>;
}

export interface UserAccessServiceController {
  loginDirectAccessGrants(request: LoginRequest): Promise<LoginResponse> | Observable<LoginResponse> | LoginResponse;

  refreshToken(request: RefreshTokenRequest): Promise<LoginResponse> | Observable<LoginResponse> | LoginResponse;

  logout(request: LogoutRequest): Promise<MessageResponse> | Observable<MessageResponse> | MessageResponse;

  register(request: RegisterRequest): Promise<MessageResponse> | Observable<MessageResponse> | MessageResponse;

  verifyToken(
    request: VerifyTokenRequest,
  ): Promise<VerifyTokenResponse> | Observable<VerifyTokenResponse> | VerifyTokenResponse;

  changePassword(
    request: ChangePasswordRequest,
  ): Promise<MessageResponse> | Observable<MessageResponse> | MessageResponse;

  sendOtp(
    request: SendVerificationCodeRequest,
  ): Promise<MessageResponse> | Observable<MessageResponse> | MessageResponse;

  getUser(request: GetUserRequest): Promise<UserResponse> | Observable<UserResponse> | UserResponse;

  getManyUsers(
    request: GetManyUsersRequest,
  ): Promise<GetManyUsersResponse> | Observable<GetManyUsersResponse> | GetManyUsersResponse;

  updateUser(request: UpdateUserRequest): Promise<UserResponse> | Observable<UserResponse> | UserResponse;

  createUser(request: CreateUserRequest): Promise<UserResponse> | Observable<UserResponse> | UserResponse;

  checkParticipantExists(
    request: CheckParticipantExistsRequest,
  ):
    | Promise<CheckParticipantExistsResponse>
    | Observable<CheckParticipantExistsResponse>
    | CheckParticipantExistsResponse;

  getManyInformationUsers(
    request: GetManyInformationUsersRequest,
  ):
    | Promise<GetManyInformationUsersResponse>
    | Observable<GetManyInformationUsersResponse>
    | GetManyInformationUsersResponse;

  getShop(request: GetShopRequest): Promise<ShopResponse> | Observable<ShopResponse> | ShopResponse;

  getManyShops(
    request: GetManyShopsRequest,
  ): Promise<GetManyShopsResponse> | Observable<GetManyShopsResponse> | GetManyShopsResponse;

  createShop(request: CreateShopRequest): Promise<ShopResponse> | Observable<ShopResponse> | ShopResponse;

  updateShop(request: UpdateShopRequest): Promise<ShopResponse> | Observable<ShopResponse> | ShopResponse;

  validateShops(
    request: ValidateShopsRequest,
  ): Promise<ValidateShopsResponse> | Observable<ValidateShopsResponse> | ValidateShopsResponse;

  getManyAddresses(
    request: GetManyAddressesRequest,
  ): Promise<GetManyAddressesResponse> | Observable<GetManyAddressesResponse> | GetManyAddressesResponse;

  getAddress(request: GetAddressRequest): Promise<AddressResponse> | Observable<AddressResponse> | AddressResponse;

  createAddress(
    request: CreateAddressRequest,
  ): Promise<AddressResponse> | Observable<AddressResponse> | AddressResponse;

  updateAddress(
    request: UpdateAddressRequest,
  ): Promise<AddressResponse> | Observable<AddressResponse> | AddressResponse;

  deleteAddress(
    request: DeleteAddressRequest,
  ): Promise<AddressResponse> | Observable<AddressResponse> | AddressResponse;
}

export function UserAccessServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      "loginDirectAccessGrants",
      "refreshToken",
      "logout",
      "register",
      "verifyToken",
      "changePassword",
      "sendOtp",
      "getUser",
      "getManyUsers",
      "updateUser",
      "createUser",
      "checkParticipantExists",
      "getManyInformationUsers",
      "getShop",
      "getManyShops",
      "createShop",
      "updateShop",
      "validateShops",
      "getManyAddresses",
      "getAddress",
      "createAddress",
      "updateAddress",
      "deleteAddress",
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("UserAccessService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("UserAccessService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const USER_ACCESS_SERVICE_NAME = "UserAccessService";
