// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               v7.35.1
// source: utility.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "UTILITY_SERVICE";

export interface GetManyNotificationsRequest {
  processId?: string | undefined;
  page: number;
  limit: number;
  userId: string;
  type?: string | undefined;
}

export interface GetManyNotificationsResponse {
  page: number;
  limit: number;
  totalItems: number;
  totalPages: number;
  notifications: NotificationResponse[];
  unreadCount: number;
}

export interface GetNotificationRequest {
  processId?: string | undefined;
  id: string;
  userId: string;
}

export interface CreateNotificationRequest {
  processId?: string | undefined;
  userId: string;
  type: string;
  title: string;
  description: string;
  link?: string | undefined;
  image?: string | undefined;
  metadata?: string | undefined;
  createdById?: string | undefined;
}

export interface ReadNotificationRequest {
  processId?: string | undefined;
  id: string[];
  updatedById?: string | undefined;
}

export interface ReadNotificationResponse {
  count: number;
}

export interface DeleteNotificationRequest {
  processId?: string | undefined;
  id: string;
  deletedById?: string | undefined;
}

export interface NotificationResponse {
  id: string;
  userId: string;
  type: string;
  title: string;
  description: string;
  link?: string | undefined;
  image?: string | undefined;
  isRead: boolean;
  metadata?: string | undefined;
  createdById?: string | undefined;
  updatedById?: string | undefined;
  deletedById?: string | undefined;
  deletedAt?: string | undefined;
  createdAt: string;
  updatedAt: string;
}

export interface CreatePresignedUrlRequest {
  processId?: string | undefined;
  userId: string;
  fileName: string;
  type: string;
  productId?: string | undefined;
}

export interface CreatePresignedUrlResponse {
  presignedUrl: string;
  url: string;
}

export interface CreateVideoRequest {
  processId?: string | undefined;
  shopId: string;
  uploadedById: string;
  productId?: string | undefined;
}

export interface GetManyVideosRequest {
  processId?: string | undefined;
  page: number;
  limit: number;
  shopId?: string | undefined;
  productId?: string | undefined;
  status?: string | undefined;
}

export interface GetManyVideosResponse {
  page: number;
  limit: number;
  totalItems: number;
  totalPages: number;
  videos: VideoResponse[];
}

export interface GetVideoRequest {
  processId?: string | undefined;
  id: string;
}

export interface GetVideoFeedRequest {
  processId?: string | undefined;
  limit: number;
  excludeIds: string[];
}

export interface UpdateVideoStatusRequest {
  processId?: string | undefined;
  id: string;
  status: string;
  duration?: number | undefined;
  width?: number | undefined;
  height?: number | undefined;
}

export interface UpdateVideoRequest {
  processId?: string | undefined;
  id: string;
  productId?: string | undefined;
  isHidden?: boolean | undefined;
}

export interface DeleteVideoRequest {
  processId?: string | undefined;
  id: string;
}

export interface VideoResponse {
  id: string;
  shopId: string;
  productId?: string | undefined;
  status: string;
  duration?: number | undefined;
  width?: number | undefined;
  height?: number | undefined;
  likeCount: number;
  uploadedById: string;
  deletedAt?: string | undefined;
  createdAt: string;
  updatedAt: string;
  presignedUrl: string;
  hlsUrl: string;
  thumbnailUrl: string;
  isHidden: boolean;
}

export interface GetManyReportsRequest {
  processId?: string | undefined;
  page: number;
  limit: number;
  userId?: string | undefined;
  status?: string | undefined;
}

export interface GetManyReportsResponse {
  page: number;
  limit: number;
  totalItems: number;
  totalPages: number;
  reports: ReportResponse[];
}

export interface GetReportRequest {
  processId?: string | undefined;
  id: string;
}

export interface CreateReportRequest {
  processId?: string | undefined;
  reporterId: string;
  targetType: string;
  targetId: string;
  category: string;
  title: string;
  description: string;
  media: string[];
}

export interface UpdateReportRequest {
  processId?: string | undefined;
  id: string;
  status: string;
  assigneeAdminId?: string | undefined;
  action?: string | undefined;
}

export interface ResolveReportRequest {
  processId?: string | undefined;
  id: string;
  action?: string | undefined;
}

export interface DeleteReportRequest {
  processId?: string | undefined;
  id: string;
}

export interface ReportResponse {
  id: string;
  reporterId: string;
  targetType: string;
  targetId: string;
  category: string;
  title: string;
  description: string;
  status: string;
  assigneeAdminId?: string | undefined;
  closedAt?: string | undefined;
  media: string[];
  action?: string | undefined;
  deletedAt?: string | undefined;
  createdAt: string;
  updatedAt: string;
}

export interface GetManyReviewsRequest {
  processId?: string | undefined;
  page: number;
  limit: number;
  productId?: string | undefined;
  sellerId?: string | undefined;
  userId?: string | undefined;
}

export interface GetManyReviewsResponse {
  page: number;
  limit: number;
  totalItems: number;
  totalPages: number;
  reviews: ReviewResponse[];
}

export interface GetReviewRequest {
  processId?: string | undefined;
  id: string;
}

export interface GetReviewByOrderItemIdRequest {
  processId?: string | undefined;
  orderItemId: string;
  userId: string;
}

export interface CreateReviewRequest {
  processId?: string | undefined;
  userId: string;
  sellerId: string;
  productId: string;
  orderId: string;
  orderItemId: string;
  rating: number;
  content?: string | undefined;
  mediaUrls: string[];
}

export interface UpdateReviewRequest {
  processId?: string | undefined;
  id: string;
  userId: string;
  content?: string | undefined;
  rating?: number | undefined;
  mediaUrls: string[];
}

export interface DeleteReviewRequest {
  processId?: string | undefined;
  id: string;
  userId: string;
}

export interface ReviewResponse {
  id: string;
  userId: string;
  sellerId: string;
  productId: string;
  orderId: string;
  orderItemId: string;
  rating: number;
  content?: string | undefined;
  mediaUrls: string[];
  deletedAt?: string | undefined;
  createdAt: string;
  updatedAt: string;
}

export interface GetProvincesRequest {
  processId?: string | undefined;
}

export interface GetProvincesResponse {
  provinces: ProvinceResponse[];
}

export interface GetDistrictsRequest {
  processId?: string | undefined;
  provinceId: number;
}

export interface GetDistrictsResponse {
  districts: DistrictResponse[];
}

export interface GetWardsRequest {
  processId?: string | undefined;
  districtId: number;
}

export interface GetWardsResponse {
  wards: WardResponse[];
}

export interface ProvinceResponse {
  id: number;
  name: string;
}

export interface DistrictResponse {
  id: number;
  name: string;
  provinceId: number;
}

export interface WardResponse {
  id: number;
  name: string;
  districtId: number;
  provinceId: number;
}

export const UTILITY_SERVICE_PACKAGE_NAME = "UTILITY_SERVICE";

/** ==================== NOTIFICATION SERVICE ====================// */

export interface NotificationServiceClient {
  getManyNotifications(request: GetManyNotificationsRequest): Observable<GetManyNotificationsResponse>;

  getNotification(request: GetNotificationRequest): Observable<NotificationResponse>;

  createNotification(request: CreateNotificationRequest): Observable<NotificationResponse>;

  readNotification(request: ReadNotificationRequest): Observable<ReadNotificationResponse>;

  deleteNotification(request: DeleteNotificationRequest): Observable<NotificationResponse>;
}

/** ==================== NOTIFICATION SERVICE ====================// */

export interface NotificationServiceController {
  getManyNotifications(
    request: GetManyNotificationsRequest,
  ): Promise<GetManyNotificationsResponse> | Observable<GetManyNotificationsResponse> | GetManyNotificationsResponse;

  getNotification(
    request: GetNotificationRequest,
  ): Promise<NotificationResponse> | Observable<NotificationResponse> | NotificationResponse;

  createNotification(
    request: CreateNotificationRequest,
  ): Promise<NotificationResponse> | Observable<NotificationResponse> | NotificationResponse;

  readNotification(
    request: ReadNotificationRequest,
  ): Promise<ReadNotificationResponse> | Observable<ReadNotificationResponse> | ReadNotificationResponse;

  deleteNotification(
    request: DeleteNotificationRequest,
  ): Promise<NotificationResponse> | Observable<NotificationResponse> | NotificationResponse;
}

export function NotificationServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      "getManyNotifications",
      "getNotification",
      "createNotification",
      "readNotification",
      "deleteNotification",
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("NotificationService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("NotificationService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const NOTIFICATION_SERVICE_NAME = "NotificationService";

/** ==================== MEDIA SERVICE ====================// */

export interface MediaServiceClient {
  createPresignedUrl(request: CreatePresignedUrlRequest): Observable<CreatePresignedUrlResponse>;
}

/** ==================== MEDIA SERVICE ====================// */

export interface MediaServiceController {
  createPresignedUrl(
    request: CreatePresignedUrlRequest,
  ): Promise<CreatePresignedUrlResponse> | Observable<CreatePresignedUrlResponse> | CreatePresignedUrlResponse;
}

export function MediaServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["createPresignedUrl"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("MediaService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("MediaService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const MEDIA_SERVICE_NAME = "MediaService";

/** ==================== VIDEO SERVICE ====================// */

export interface VideoServiceClient {
  createVideo(request: CreateVideoRequest): Observable<VideoResponse>;

  getManyVideos(request: GetManyVideosRequest): Observable<GetManyVideosResponse>;

  getVideo(request: GetVideoRequest): Observable<VideoResponse>;

  getVideoFeed(request: GetVideoFeedRequest): Observable<GetManyVideosResponse>;

  updateVideo(request: UpdateVideoRequest): Observable<VideoResponse>;

  updateVideoStatus(request: UpdateVideoStatusRequest): Observable<VideoResponse>;

  deleteVideo(request: DeleteVideoRequest): Observable<VideoResponse>;
}

/** ==================== VIDEO SERVICE ====================// */

export interface VideoServiceController {
  createVideo(request: CreateVideoRequest): Promise<VideoResponse> | Observable<VideoResponse> | VideoResponse;

  getManyVideos(
    request: GetManyVideosRequest,
  ): Promise<GetManyVideosResponse> | Observable<GetManyVideosResponse> | GetManyVideosResponse;

  getVideo(request: GetVideoRequest): Promise<VideoResponse> | Observable<VideoResponse> | VideoResponse;

  getVideoFeed(
    request: GetVideoFeedRequest,
  ): Promise<GetManyVideosResponse> | Observable<GetManyVideosResponse> | GetManyVideosResponse;

  updateVideo(request: UpdateVideoRequest): Promise<VideoResponse> | Observable<VideoResponse> | VideoResponse;

  updateVideoStatus(
    request: UpdateVideoStatusRequest,
  ): Promise<VideoResponse> | Observable<VideoResponse> | VideoResponse;

  deleteVideo(request: DeleteVideoRequest): Promise<VideoResponse> | Observable<VideoResponse> | VideoResponse;
}

export function VideoServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      "createVideo",
      "getManyVideos",
      "getVideo",
      "getVideoFeed",
      "updateVideo",
      "updateVideoStatus",
      "deleteVideo",
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("VideoService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("VideoService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const VIDEO_SERVICE_NAME = "VideoService";

/** ==================== REPORT SERVICE ====================// */

export interface ReportServiceClient {
  getManyReports(request: GetManyReportsRequest): Observable<GetManyReportsResponse>;

  getReport(request: GetReportRequest): Observable<ReportResponse>;

  createReport(request: CreateReportRequest): Observable<ReportResponse>;

  updateReport(request: UpdateReportRequest): Observable<ReportResponse>;

  resolveReport(request: ResolveReportRequest): Observable<ReportResponse>;

  deleteReport(request: DeleteReportRequest): Observable<ReportResponse>;
}

/** ==================== REPORT SERVICE ====================// */

export interface ReportServiceController {
  getManyReports(
    request: GetManyReportsRequest,
  ): Promise<GetManyReportsResponse> | Observable<GetManyReportsResponse> | GetManyReportsResponse;

  getReport(request: GetReportRequest): Promise<ReportResponse> | Observable<ReportResponse> | ReportResponse;

  createReport(request: CreateReportRequest): Promise<ReportResponse> | Observable<ReportResponse> | ReportResponse;

  updateReport(request: UpdateReportRequest): Promise<ReportResponse> | Observable<ReportResponse> | ReportResponse;

  resolveReport(request: ResolveReportRequest): Promise<ReportResponse> | Observable<ReportResponse> | ReportResponse;

  deleteReport(request: DeleteReportRequest): Promise<ReportResponse> | Observable<ReportResponse> | ReportResponse;
}

export function ReportServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      "getManyReports",
      "getReport",
      "createReport",
      "updateReport",
      "resolveReport",
      "deleteReport",
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("ReportService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("ReportService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const REPORT_SERVICE_NAME = "ReportService";

/** ==================== REVIEW SERVICE ====================// */

export interface ReviewServiceClient {
  getManyReviews(request: GetManyReviewsRequest): Observable<GetManyReviewsResponse>;

  getReview(request: GetReviewRequest): Observable<ReviewResponse>;

  getReviewByOrderItemId(request: GetReviewByOrderItemIdRequest): Observable<ReviewResponse>;

  createReview(request: CreateReviewRequest): Observable<ReviewResponse>;

  updateReview(request: UpdateReviewRequest): Observable<ReviewResponse>;

  deleteReview(request: DeleteReviewRequest): Observable<ReviewResponse>;
}

/** ==================== REVIEW SERVICE ====================// */

export interface ReviewServiceController {
  getManyReviews(
    request: GetManyReviewsRequest,
  ): Promise<GetManyReviewsResponse> | Observable<GetManyReviewsResponse> | GetManyReviewsResponse;

  getReview(request: GetReviewRequest): Promise<ReviewResponse> | Observable<ReviewResponse> | ReviewResponse;

  getReviewByOrderItemId(
    request: GetReviewByOrderItemIdRequest,
  ): Promise<ReviewResponse> | Observable<ReviewResponse> | ReviewResponse;

  createReview(request: CreateReviewRequest): Promise<ReviewResponse> | Observable<ReviewResponse> | ReviewResponse;

  updateReview(request: UpdateReviewRequest): Promise<ReviewResponse> | Observable<ReviewResponse> | ReviewResponse;

  deleteReview(request: DeleteReviewRequest): Promise<ReviewResponse> | Observable<ReviewResponse> | ReviewResponse;
}

export function ReviewServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      "getManyReviews",
      "getReview",
      "getReviewByOrderItemId",
      "createReview",
      "updateReview",
      "deleteReview",
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("ReviewService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("ReviewService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const REVIEW_SERVICE_NAME = "ReviewService";

/** ==================== LOCATION SERVICE ====================// */

export interface LocationServiceClient {
  getProvinces(request: GetProvincesRequest): Observable<GetProvincesResponse>;

  getDistricts(request: GetDistrictsRequest): Observable<GetDistrictsResponse>;

  getWards(request: GetWardsRequest): Observable<GetWardsResponse>;
}

/** ==================== LOCATION SERVICE ====================// */

export interface LocationServiceController {
  getProvinces(
    request: GetProvincesRequest,
  ): Promise<GetProvincesResponse> | Observable<GetProvincesResponse> | GetProvincesResponse;

  getDistricts(
    request: GetDistrictsRequest,
  ): Promise<GetDistrictsResponse> | Observable<GetDistrictsResponse> | GetDistrictsResponse;

  getWards(request: GetWardsRequest): Promise<GetWardsResponse> | Observable<GetWardsResponse> | GetWardsResponse;
}

export function LocationServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["getProvinces", "getDistricts", "getWards"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("LocationService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("LocationService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const LOCATION_SERVICE_NAME = "LocationService";
