// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               v7.35.1
// source: wallet.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "WALLET_SERVICE";

export interface GetMyWalletRequest {
  processId?: string | undefined;
  userId: string;
}

export interface AdjustWalletRequest {
  processId?: string | undefined;
  userId: string;
  /** CREDIT | DEBIT */
  type: string;
  /** ORDER_REWARD | REVIEW_REWARD | PROMOTION_GIFT | REFERRAL | TOPUP | REFUND | ORDER_PAYMENT | SYSTEM | OTHER */
  source: string;
  referenceId?: string | undefined;
  amount: number;
  description: string;
}

export interface GetMyTransactionsRequest {
  processId?: string | undefined;
  userId: string;
  page: number;
  limit: number;
  type?: string | undefined;
  source?: string | undefined;
}

export interface WalletResponse {
  id: string;
  userId: string;
  balance: number;
  createdAt: string;
  updatedAt: string;
}

export interface WalletTransactionResponse {
  id: string;
  walletId: string;
  userId: string;
  type: string;
  source: string;
  referenceId?: string | undefined;
  amount: number;
  balanceAfter: number;
  description: string;
  createdAt: string;
}

export interface GetMyTransactionsResponse {
  page: number;
  limit: number;
  totalItems: number;
  totalPages: number;
  transactions: WalletTransactionResponse[];
}

export interface GetShopCreditRequest {
  processId?: string | undefined;
  shopId: string;
}

export interface AdjustShopCreditRequest {
  processId?: string | undefined;
  shopId: string;
  /** CREDIT | DEBIT */
  type: string;
  /** ORDER_REVENUE | PLATFORM_FEE | TAX_WITHHOLDING | WITHDRAWAL | REFUND | SYSTEM | OTHER */
  source: string;
  referenceId?: string | undefined;
  amount: number;
  description: string;
}

export interface GetShopCreditTransactionsRequest {
  processId?: string | undefined;
  shopId: string;
  page: number;
  limit: number;
  type?: string | undefined;
  source?: string | undefined;
}

export interface GetShopRevenueSummaryRequest {
  processId?: string | undefined;
  shopId: string;
  days: number;
}

export interface CreditResponse {
  id: string;
  shopId: string;
  balance: number;
  createdAt: string;
  updatedAt: string;
}

export interface CreditTransactionResponse {
  id: string;
  creditId: string;
  shopId: string;
  type: string;
  source: string;
  referenceId?: string | undefined;
  amount: number;
  balanceAfter: number;
  description: string;
  createdAt: string;
}

export interface GetShopCreditTransactionsResponse {
  page: number;
  limit: number;
  totalItems: number;
  totalPages: number;
  transactions: CreditTransactionResponse[];
}

export interface ShopRevenueDayPoint {
  date: string;
  amount: number;
}

export interface GetShopRevenueSummaryResponse {
  days: number;
  totalRevenue: number;
  points: ShopRevenueDayPoint[];
}

export interface CreateShopPayoutRequest {
  processId?: string | undefined;
  shopId: string;
  amount: number;
  bankName: string;
  accountNumber: string;
  accountHolder: string;
  note?: string | undefined;
}

export interface GetShopPayoutByIdRequest {
  processId?: string | undefined;
  shopId: string;
  payoutId: string;
}

export interface GetShopPayoutsRequest {
  processId?: string | undefined;
  shopId?: string | undefined;
  page: number;
  limit: number;
  status?: string | undefined;
}

export interface UpdateShopPayoutStatusRequest {
  processId?: string | undefined;
  shopId: string;
  payoutId: string;
  status: string;
  rejectReason?: string | undefined;
}

export interface DeleteShopPayoutRequest {
  processId?: string | undefined;
  shopId: string;
  payoutId: string;
}

export interface ShopPayoutResponse {
  id: string;
  creditId: string;
  shopId: string;
  amount: number;
  bankName: string;
  accountNumber: string;
  accountHolder: string;
  note?: string | undefined;
  status: string;
  rejectReason?: string | undefined;
  processedAt?: string | undefined;
  createdAt: string;
  updatedAt: string;
}

export interface GetShopPayoutsResponse {
  page: number;
  limit: number;
  totalItems: number;
  totalPages: number;
  payouts: ShopPayoutResponse[];
}

export interface RecordPlatformLedgerRequest {
  processId?: string | undefined;
  orderId: string;
  shopId: string;
  grossAmount: number;
  commissionRate: number;
  commissionFee: number;
  taxRate: number;
  taxWithheld: number;
  netSellerAmount: number;
}

export interface PlatformLedgerResponse {
  id: string;
  orderId: string;
  shopId: string;
  grossAmount: number;
  commissionRate: number;
  commissionFee: number;
  taxRate: number;
  taxWithheld: number;
  netSellerAmount: number;
  createdAt: string;
}

export interface GetPlatformRevenueSummaryRequest {
  processId?: string | undefined;
  startDate?: string | undefined;
  endDate?: string | undefined;
  shopId?: string | undefined;
}

export interface GetPlatformRevenueSummaryResponse {
  totalGMV: number;
  totalCommission: number;
  totalTaxWithheld: number;
  totalNetSellerAmount: number;
  totalPendingPayouts: number;
}

export interface GetPlatformLedgerListRequest {
  processId?: string | undefined;
  page: number;
  limit: number;
  shopId?: string | undefined;
  startDate?: string | undefined;
  endDate?: string | undefined;
  sortBy?: string | undefined;
  sortOrder?: string | undefined;
}

export interface GetPlatformLedgerListResponse {
  page: number;
  limit: number;
  totalItems: number;
  totalPages: number;
  items: PlatformLedgerResponse[];
}

export const WALLET_SERVICE_PACKAGE_NAME = "WALLET_SERVICE";

export interface WalletModuleClient {
  getMyWallet(request: GetMyWalletRequest): Observable<WalletResponse>;

  adjustWallet(request: AdjustWalletRequest): Observable<WalletResponse>;

  getMyTransactions(request: GetMyTransactionsRequest): Observable<GetMyTransactionsResponse>;
}

export interface WalletModuleController {
  getMyWallet(request: GetMyWalletRequest): Promise<WalletResponse> | Observable<WalletResponse> | WalletResponse;

  adjustWallet(request: AdjustWalletRequest): Promise<WalletResponse> | Observable<WalletResponse> | WalletResponse;

  getMyTransactions(
    request: GetMyTransactionsRequest,
  ): Promise<GetMyTransactionsResponse> | Observable<GetMyTransactionsResponse> | GetMyTransactionsResponse;
}

export function WalletModuleControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["getMyWallet", "adjustWallet", "getMyTransactions"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("WalletModule", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("WalletModule", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const WALLET_MODULE_SERVICE_NAME = "WalletModule";

export interface CreditModuleClient {
  getShopCredit(request: GetShopCreditRequest): Observable<CreditResponse>;

  adjustShopCredit(request: AdjustShopCreditRequest): Observable<CreditResponse>;

  getShopCreditTransactions(request: GetShopCreditTransactionsRequest): Observable<GetShopCreditTransactionsResponse>;

  getShopRevenueSummary(request: GetShopRevenueSummaryRequest): Observable<GetShopRevenueSummaryResponse>;
}

export interface CreditModuleController {
  getShopCredit(request: GetShopCreditRequest): Promise<CreditResponse> | Observable<CreditResponse> | CreditResponse;

  adjustShopCredit(
    request: AdjustShopCreditRequest,
  ): Promise<CreditResponse> | Observable<CreditResponse> | CreditResponse;

  getShopCreditTransactions(
    request: GetShopCreditTransactionsRequest,
  ):
    | Promise<GetShopCreditTransactionsResponse>
    | Observable<GetShopCreditTransactionsResponse>
    | GetShopCreditTransactionsResponse;

  getShopRevenueSummary(
    request: GetShopRevenueSummaryRequest,
  ): Promise<GetShopRevenueSummaryResponse> | Observable<GetShopRevenueSummaryResponse> | GetShopRevenueSummaryResponse;
}

export function CreditModuleControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      "getShopCredit",
      "adjustShopCredit",
      "getShopCreditTransactions",
      "getShopRevenueSummary",
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("CreditModule", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("CreditModule", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const CREDIT_MODULE_SERVICE_NAME = "CreditModule";

export interface PayoutModuleClient {
  createShopPayout(request: CreateShopPayoutRequest): Observable<ShopPayoutResponse>;

  getShopPayoutById(request: GetShopPayoutByIdRequest): Observable<ShopPayoutResponse>;

  getShopPayouts(request: GetShopPayoutsRequest): Observable<GetShopPayoutsResponse>;

  updateShopPayoutStatus(request: UpdateShopPayoutStatusRequest): Observable<ShopPayoutResponse>;

  deleteShopPayout(request: DeleteShopPayoutRequest): Observable<ShopPayoutResponse>;
}

export interface PayoutModuleController {
  createShopPayout(
    request: CreateShopPayoutRequest,
  ): Promise<ShopPayoutResponse> | Observable<ShopPayoutResponse> | ShopPayoutResponse;

  getShopPayoutById(
    request: GetShopPayoutByIdRequest,
  ): Promise<ShopPayoutResponse> | Observable<ShopPayoutResponse> | ShopPayoutResponse;

  getShopPayouts(
    request: GetShopPayoutsRequest,
  ): Promise<GetShopPayoutsResponse> | Observable<GetShopPayoutsResponse> | GetShopPayoutsResponse;

  updateShopPayoutStatus(
    request: UpdateShopPayoutStatusRequest,
  ): Promise<ShopPayoutResponse> | Observable<ShopPayoutResponse> | ShopPayoutResponse;

  deleteShopPayout(
    request: DeleteShopPayoutRequest,
  ): Promise<ShopPayoutResponse> | Observable<ShopPayoutResponse> | ShopPayoutResponse;
}

export function PayoutModuleControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      "createShopPayout",
      "getShopPayoutById",
      "getShopPayouts",
      "updateShopPayoutStatus",
      "deleteShopPayout",
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("PayoutModule", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("PayoutModule", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const PAYOUT_MODULE_SERVICE_NAME = "PayoutModule";

export interface PlatformLedgerModuleClient {
  recordPlatformLedger(request: RecordPlatformLedgerRequest): Observable<PlatformLedgerResponse>;

  getPlatformRevenueSummary(request: GetPlatformRevenueSummaryRequest): Observable<GetPlatformRevenueSummaryResponse>;

  getPlatformLedgerList(request: GetPlatformLedgerListRequest): Observable<GetPlatformLedgerListResponse>;
}

export interface PlatformLedgerModuleController {
  recordPlatformLedger(
    request: RecordPlatformLedgerRequest,
  ): Promise<PlatformLedgerResponse> | Observable<PlatformLedgerResponse> | PlatformLedgerResponse;

  getPlatformRevenueSummary(
    request: GetPlatformRevenueSummaryRequest,
  ):
    | Promise<GetPlatformRevenueSummaryResponse>
    | Observable<GetPlatformRevenueSummaryResponse>
    | GetPlatformRevenueSummaryResponse;

  getPlatformLedgerList(
    request: GetPlatformLedgerListRequest,
  ): Promise<GetPlatformLedgerListResponse> | Observable<GetPlatformLedgerListResponse> | GetPlatformLedgerListResponse;
}

export function PlatformLedgerModuleControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["recordPlatformLedger", "getPlatformRevenueSummary", "getPlatformLedgerList"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("PlatformLedgerModule", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("PlatformLedgerModule", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const PLATFORM_LEDGER_MODULE_SERVICE_NAME = "PlatformLedgerModule";
