// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               v7.34.1
// source: wallet.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "WALLET_SERVICE";

/** Request Messages */
export interface GetMyWalletRequest {
  processId?: string | undefined;
  userId: string;
}

export interface AdjustWalletRequest {
  processId?: string | undefined;
  userId: string;
  /** CREDIT | DEBIT */
  type: string;
  /** ORDER_REWARD | REVIEW_REWARD | PROMOTION_GIFT | REFERRAL | TOPUP | REFUND | ORDER_PAYMENT | SYSTEM | OTHER */
  source: string;
  referenceId?: string | undefined;
  amount: number;
  description: string;
}

export interface GetMyTransactionsRequest {
  processId?: string | undefined;
  userId: string;
  page: number;
  limit: number;
  type?: string | undefined;
  source?: string | undefined;
}

/** Response Messages */
export interface WalletResponse {
  id: string;
  userId: string;
  balance: number;
  createdAt: string;
  updatedAt: string;
}

export interface WalletTransactionResponse {
  id: string;
  walletId: string;
  userId: string;
  type: string;
  source: string;
  referenceId?: string | undefined;
  amount: number;
  balanceAfter: number;
  description: string;
  createdAt: string;
}

export interface GetMyTransactionsResponse {
  page: number;
  limit: number;
  totalItems: number;
  totalPages: number;
  transactions: WalletTransactionResponse[];
}

export const WALLET_SERVICE_PACKAGE_NAME = "WALLET_SERVICE";

export interface WalletModuleClient {
  getMyWallet(request: GetMyWalletRequest): Observable<WalletResponse>;

  adjustWallet(request: AdjustWalletRequest): Observable<WalletResponse>;

  getMyTransactions(request: GetMyTransactionsRequest): Observable<GetMyTransactionsResponse>;
}

export interface WalletModuleController {
  getMyWallet(request: GetMyWalletRequest): Promise<WalletResponse> | Observable<WalletResponse> | WalletResponse;

  adjustWallet(request: AdjustWalletRequest): Promise<WalletResponse> | Observable<WalletResponse> | WalletResponse;

  getMyTransactions(
    request: GetMyTransactionsRequest,
  ): Promise<GetMyTransactionsResponse> | Observable<GetMyTransactionsResponse> | GetMyTransactionsResponse;
}

export function WalletModuleControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["getMyWallet", "adjustWallet", "getMyTransactions"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("WalletModule", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("WalletModule", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const WALLET_MODULE_SERVICE_NAME = "WalletModule";
