import type { Product } from './ProductCard';

const IMG = (q: string, seed: number) =>
  `https://picsum.photos/seed/${encodeURIComponent(q)}-${seed}/600/600`;

export const CATEGORIES = [
  { name: 'Thời trang', icon: '👕', slug: 'thoi-trang' },
  { name: 'Điện tử', icon: '📱', slug: 'dien-tu' },
  { name: 'Gia dụng', icon: '🍳', slug: 'gia-dung' },
  { name: 'Mẹ & Bé', icon: '🍼', slug: 'me-be' },
  { name: 'Sức khỏe', icon: '💊', slug: 'suc-khoe' },
  { name: 'Sách', icon: '📚', slug: 'sach' },
  { name: 'Thể thao', icon: '⚽', slug: 'the-thao' },
  { name: 'Mỹ phẩm', icon: '💄', slug: 'my-pham' },
  { name: 'Đồ chơi', icon: '🧸', slug: 'do-choi' },
  { name: 'Xe cộ', icon: '🚗', slug: 'xe-co' },
];

export const PRODUCTS: Product[] = [
  {
    id: 'p1',
    name: 'Áo thun cotton nam form rộng phong cách Hàn Quốc',
    price: 159000,
    oldPrice: 249000,
    rating: 4.8,
    sold: '12.5k',
    discount: 36,
    image: IMG('aothun', 1),
  },
  {
    id: 'p2',
    name: 'Tai nghe Bluetooth không dây chống ồn chủ động',
    price: 1290000,
    oldPrice: 1990000,
    rating: 4.9,
    sold: '8.2k',
    discount: 35,
    image: IMG('headphone', 2),
  },
  {
    id: 'p3',
    name: 'Nồi chiên không dầu 5L điều khiển cảm ứng',
    price: 1690000,
    rating: 4.7,
    sold: '3.4k',
    image: IMG('airfryer', 3),
  },
  {
    id: 'p4',
    name: 'Tay cầm chơi game không dây DualShock 5',
    price: 1690000,
    oldPrice: 2100000,
    rating: 5.0,
    sold: '320',
    discount: 20,
    image: IMG('gamepad', 4),
  },
  {
    id: 'p5',
    name: 'Bộ 3 khăn tắm cotton sợi tre siêu mềm mịn',
    price: 120000,
    rating: 4.9,
    sold: '2.1k',
    image: IMG('towel', 5),
  },
  {
    id: 'p6',
    name: 'Giày sneaker thể thao nam đế cao chống trượt',
    price: 459000,
    oldPrice: 799000,
    rating: 4.6,
    sold: '5.7k',
    discount: 42,
    image: IMG('sneaker', 6),
  },
  {
    id: 'p7',
    name: 'Đồng hồ thông minh theo dõi sức khỏe IP68',
    price: 890000,
    oldPrice: 1490000,
    rating: 4.8,
    sold: '9.3k',
    discount: 40,
    image: IMG('smartwatch', 7),
  },
  {
    id: 'p8',
    name: 'Bình giữ nhiệt inox 304 dung tích 750ml',
    price: 199000,
    rating: 4.9,
    sold: '15k',
    image: IMG('bottle', 8),
    badge: 'Yêu thích',
  },
  {
    id: 'p9',
    name: 'Balo laptop chống nước 15.6 inch nhiều ngăn',
    price: 359000,
    oldPrice: 599000,
    rating: 4.7,
    sold: '6.1k',
    discount: 40,
    image: IMG('backpack', 9),
  },
  {
    id: 'p10',
    name: 'Son lì lâu trôi cao cấp 12 màu trendy 2024',
    price: 89000,
    oldPrice: 159000,
    rating: 4.9,
    sold: '22k',
    discount: 44,
    image: IMG('lipstick', 10),
  },
  {
    id: 'p11',
    name: 'Bàn phím cơ Gaming RGB switch quang học',
    price: 690000,
    oldPrice: 1190000,
    rating: 4.8,
    sold: '1.8k',
    discount: 42,
    image: IMG('keyboard', 11),
  },
  {
    id: 'p12',
    name: 'Đèn led để bàn cảm ứng chống cận thị 3 chế độ',
    price: 249000,
    rating: 4.7,
    sold: '4.5k',
    image: IMG('lamp', 12),
  },
];
