apiVersion: apps/v1
kind: Deployment
metadata:
  name: utility-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: utility-service
  template:
    metadata:
      labels:
        app: utility-service
    spec:
      serviceAccountName: hacmieu-sa
      containers:
        - name: utility-service
          image: public.ecr.aws/h5u5b6t3/hacmieu/utility-service:latest
          imagePullPolicy: Always
          env:
            - name: UTILITY_SERVICE_GRPC_URL
              value: '0.0.0.0:5007'
          envFrom:
            - secretRef:
                name: hacmieu-secrets
          ports:
            - containerPort: 3007
            - containerPort: 5007
          resources:
            requests:
              cpu: '250m'
              memory: '512Mi'
            limits:
              cpu: '500m'
              memory: '1Gi'
